### PR TITLE
feat(web-react): adds the possibility to track events through GA4

### PR DESCRIPTION
**Pull request by PatrickfBraz**
## Context

These changes are intended to allow the sending of events from the platform to GA4.

> NOTE:  GA3 is no longer supported

## Checklist

- [x] The PR conforms to DataHub's [Contributing Guideline](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [x] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable). If a new feature has been added a Usage Guide has been added for the same.
- [ ] For any breaking change/potential downtime/deprecation/big changes an entry has been made in [Updating DataHub](https://github.com/datahub-project/datahub/blob/master/docs/how/updating-datahub.md)

### CODE REVIEW

**Comment by PatrickfBraz** [comment]
I'm still working on this PR

**Comment by hsheth2** [comment]
@PatrickfBraz is this ready for review?

**Comment by PatrickfBraz** [comment]
Yes @hsheth2. Is ready!
I would even like opinions on maybe there is another (better) way to allow GA4 and GA3

**Comment by PatrickfBraz** [comment]
@chriscollins3456 @hsheth2 
Since GA3 has been deactivated, I'm going to change my PR to refactor the tracking metrics for GA4 only. All good?

**Comment by hsheth2** [comment]
@PatrickfBraz yup that sounds good to me!

**Comment by PatrickfBraz** [comment]
@chriscollins3456 @hsheth2 
I think the PR is ready now. Sorry for the delay :sweat_smile:

**Comment by hsheth2** [comment]
Google analytics 3 has been fully sunset and no longer accepts events, so it should be fine

**Comment by hsheth2** [comment]
@PatrickfBraz one last thing here: could you add a note to `docs/updating-datahub.md`?

Other than that, this should be good to merge. Not sure why we've let it linger for so long - that's entirely our bad.

**Review by chriscollins3456 — APPROVED** [review]
this looks good! since google analytics 3 is fully sunsetted and they [stopped accepting new data in july 2023](https://support.google.com/analytics/answer/11583528?hl=en), i think we're safe to merge this.

either no one must have been using ga3 with datahub or their analytics have been broken for a year.

I'll add an update to updating-datahub.md myself

**Comment by MatMoore** [comment]
Hi @chriscollins3456 is there anything stopping this being merged? We'd also like to make use of GA4 and this PR looks like it does the job

**Comment by chriscollins3456** [comment]
noticed some CI failures and just pushed up hopefully the final fix then will merge

**Pull request merged**
