### PR TITLE
feat(graphql): Support START_WITH and END_WITH operator in GraphQL API

### PR DESCRIPTION
**Pull request by milindgupta**
Small PR for adding the start_with and end_with operator in GraphQL API

## Checklist

- [ ] The PR conforms to DataHub's [Contributing Guideline](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [ ] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable). If a new feature has been added a Usage Guide has been added for the same.
- [ ] For any breaking change/potential downtime/deprecation/big changes an entry has been made in [Updating DataHub](https://github.com/datahub-project/datahub/blob/master/docs/how/updating-datahub.md)

## Summary by CodeRabbit

- **New Features**
	- Introduced two new filtering options (`START_WITH` and `END_WITH`) for enhanced string query capabilities in the GraphQL API, providing users with more flexibility in their search operations.

### CODE REVIEW

**Review by udbhav-hbk — APPROVED** [review]

**Comment by david-leifker** [comment]
Note that while I am not sure why it was excluded, I do see a performance warning on the implementation of those conditions [here](https://github.com/datahub-project/datahub/blob/a5a33f074b93132eb9692925ddc3deeac0f16781/metadata-io/src/main/java/com/linkedin/metadata/search/utils/ESUtils.java#L234).

**Comment by milindgupta9** [comment]
> Note that while I am not sure why it was excluded, I do see a performance warning on the implementation of those conditions [here](https://github.com/datahub-project/datahub/blob/a5a33f074b93132eb9692925ddc3deeac0f16781/metadata-io/src/main/java/com/linkedin/metadata/search/utils/ESUtils.java#L234).

@david-leifker  caould you help us with the issue here

**Comment by david-leifker** [comment]
@milindgupta9 - Please run `./gradlew spotlessApply --rerun-tasks` to fix the linting errors. I would also rebase with the latest from `master` and lets see if the tests work.

From the logs:

[> Task :metadata-service:restli-api:spotlessJava FAILED](https://github.com/datahub-project/datahub/actions/runs/10155880526/job/28427095444?pr=11026#step:7:2434)

**Comment by milindgupta9** [comment]
@david-leifker  I ran ./gradlew spotlessApply --rerun-tasks in my local and it successfully passed.

**Comment by milindgupta9** [comment]
@david-leifker anything that I can do here as it doesn't seem to be the issue with linting errors.

**Comment by milindgupta9** [comment]
@david-leifker could you please help us here?

**Comment by david-leifker** [comment]
Resolved the 1 conflict with the main branch, tests running.....

**Review by david-leifker — APPROVED** [review]

**Comment by milindgupta9** [comment]
Thanks David, I was not able to see these changes. Thanks for resolving them.

**Pull request merged**
