### PR TITLE
feat(bigquery): excluding projects without any datasets from ingestion

### PR DESCRIPTION
**Pull request by upendrao**
## Checklist

- [x] The PR conforms to DataHub's [Contributing Guideline](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [x] Links to related issues (if applicable)
- [x] Tests for the changes have been added/updated (if applicable)
- [x] Docs related to the changes have been added/updated (if applicable). If a new feature has been added a Usage Guide has been added for the same.
- [x] For any breaking change/potential downtime/deprecation/big changes an entry has been made in [Updating DataHub](https://github.com/datahub-project/datahub/blob/master/docs/how/updating-datahub.md)

- Related feature request
https://feature-requests.datahubproject.io/p/skip-empty-datasets-and-projects-in-bigquery-metadata-ingestion

### CODE REVIEW

**Comment by hsheth2** [comment]
@upendrao could you explain the motivation here a bit more? I'm confused about why this is the preferred approach over specifying `project_ids`

**Comment by upendrao** [comment]
Hi @hsheth2, thanks for taking a look at the PR.
The motivation is to be able to filter out projects without any datasets when `project_id_pattern` is used to specify a list of allowed GCP projects as empty projects without any data is noise to the users.

**Background**: I work in an organisation where we have a model of using a separate GCP projects for each application to be able to streamline resource usage/access/costs. So some of the applications stream their data to BigQuery and some do not and the list of such projects is ever increasing. So we have to skim through all the projects in the organisation to look for metadata.

**Comment by hsheth2** [comment]
Can't you just add the projects that you don't want to the `project_id_pattern` deny list? Once you do that, stateful ingestion will automatically soft delete anything that was previously incorrectly ingested.

**Comment by upendrao** [comment]
Unfortunately not, as the denied list is dynamic with projects being added/removed on a daily basis

**Comment by upendrao** [comment]
A typical project name in my org looks follows this pattern org-<app-specific-id>-<dev|staging|production>
I use a `project_id_pattern` '`^org-.*-dev$`' to specify all development projects 
Similarly '`^org-.*-staging$`' and '`^org-.*-production$`' for TEST and PRODUCTION projects.
So the `<app-specific-id>` does not give me any clue on if this project has BQ data or not as the some apps choose to write data and some do not.

**Comment by upendrao** [comment]
@hsheth2 Do you have any more comments on this PR? I'm curious to get this going.

**Comment by hsheth2** [comment]
@upendrao I'm honestly kinda conflicted on this one. 

On one hand, the use case makes sense and I understand why you'd want this.

On the other hand, if you explicitly listed a given project in project_ids or allowed in your project patterns, it feels somewhat incorrect to exclude the container entirely. It also sets a precedent of supporting an `exclude_empty_*` for across BigQuery datasets and other container types in other sources. For that reason, I do wonder if it would be better implemented as a transformer.

I am leaning towards accepting this PR, but want to get @asikowitz's thoughts on it first. If we accept it, we'll probably mark the config as experimental to give us the flexibility to turn it into a transformer in the future.

**Review by asikowitz — APPROVED** [review]

**Comment by asikowitz** [comment]
I agree with Harshal that it's awkward when specifying project ids manually. That being said, I think the problem ultimately lies with our error handling / presentatino, i.e. ability to call out if we omitted a project id you specified because it lacked datasets, and not with the idea of omitting projects lacking datasets itself.

**Comment by upendrao** [comment]
@asikowitz and @hsheth2 Thanks for your feedback.
What would be the next step in this PR.
Is there anything I need to do for getting this merged to master.
I'm curious about the timeline when it can make it to possible upcoming release.

**Comment by upendrao** [comment]
Hi @hsheth2, I am just trying to get better understanding on your proposal to use transformers for this case. As far I understand a transformer can act upon metadata-change-events, related to this case it would be metadata-ingestion-events that you anticipate to transform. Since the state of a container(bigquery-project in this case) being empty or not is known only after the ingestion activity is finished. This requires the transformer to manage the state for each such container and trigger a delete operation finally. And this needs to be done after every ingestion cycle which is daily for us here. I think this is not very efficient against preventing the unwanted containers getting into the system. 
Please enlighten me if you have better ways of doing it with transformers :-)

**Comment by asikowitz** [comment]
@upendrao I had to make some logical changes due to refactoring we did on the bigquery source. However, I think this still accomplishes your goals

**Comment by asikowitz** [comment]
Merging thru CI failure that looks unrelated

**Comment by upendrao** [comment]
Hi @maggiehays wondering if this PR is eligible for hacktoberfest?

**Pull request merged**
