### PR TITLE
fix(ui): checks truthy value for last ingested

### PR DESCRIPTION
**Pull request by pinakipb2**
## Checklist

- [x] The PR conforms to DataHub's [Contributing Guideline](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [ ] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable). If a new feature has been added a Usage Guide has been added for the same.
- [ ] For any breaking change/potential downtime/deprecation/big changes an entry has been made in [Updating DataHub](https://github.com/datahub-project/datahub/blob/master/docs/how/updating-datahub.md)

When lastIngested is 0, 0 gets rendered in the screen.

## Summary by CodeRabbit

- **Bug Fixes**
  - Improved the reliability of displaying the last ingested date by updating the conditional rendering logic.

### CODE REVIEW

**Comment by rtekal** [comment]
@chriscollins3456, when you get a chance, can you please approve and merge this PR.  Thank you in advance.

**Review by hsheth2 — APPROVED** [review]

**Comment by rtekal** [comment]
@hsheth2 Thank you for approving the PR.  When you get a chance, please merge the PR.

**Comment by hsheth2** [comment]
Looks like CI is failing due to a lint issue

```
[warn] Code style issues found in the above file. Forgot to run Prettier?

> Task :datahub-web-react:yarnLint FAILED
```

**Comment by pinakipb2** [comment]
> Looks like CI is failing due to a lint issue
> 
> ```
> [warn] Code style issues found in the above file. Forgot to run Prettier?
> 
> > Task :datahub-web-react:yarnLint FAILED
> ```

Its addressed.
Thanks !

**Comment by rtekal** [comment]
@hsheth2, I think you cancelled the workflow and it is not re-running.  Or actually my question: you aeed the label  'merge-pending-ci', how does it come out of 'pending' state?

**Pull request merged**
