### PR TITLE
Feature/custom highlight on search 

### PR DESCRIPTION
**Pull request by arpanchakra29**
This PR aims to introduce a new feature to enable custom highlighting while searching via Datahub native graphql queries .
By default , Datahub graphql engine adds all searchable fields inside elastic search highlighter which adds  huge overhead if the search universe is large and have enriched description on column level . Because for each field mentioned in the highlighter , Elastic search reruns another in memory indexing per entity .

We have introduced a new field called **customHighlightingFields** where user can pass the fields which they want to highlight , we then only take these fields in to account for search highlighting . This features enables faster retrieval of data and offers customization . 

Please refer below on the usage -
**Highlight with Valid Field **

custom_highlighting_with_valid_field

**Custom Highlight when highlighting disabled**

custom_highlighting_with_highlighting_disabled

**Custom Highlight  with empty fields array** ( It default backs to original highlighting in case of empty array or invalid items)

custom_highlighting_with_empty_fields_array

### CODE REVIEW

**Review by david-leifker — APPROVED** [review]
LGTM!

**Comment by david-leifker** [comment]
Looks like a linting failure. This can be fixed up by running and commiting the changes from `./gradlew spotlessApply --rerun-tasks`

**Comment by arpanchakra29** [comment]
thank you @david-leifker  . have updated with lint commit .

**Review by david-leifker — APPROVED** [review]

**Comment by david-leifker** [comment]
Looks like some missing files due to the schema change.
[Log](https://github.com/datahub-project/datahub/actions/runs/10795960178/job/29947006714?pr=11339#step:12:46)
```
M metadata-service/restli-api/src/main/snapshot/com.linkedin.entity.aspects.snapshot.json M metadata-service/restli-api/src/main/snapshot/com.linkedin.entity.entities.snapshot.json M metadata-service/restli-api/src/main/snapshot/com.linkedin.entity.runs.snapshot.json M metadata-service/restli-api/src/main/snapshot/com.linkedin.operations.operations.snapshot.json M metadata-service/restli-api/src/main/snapshot/com.linkedin.platform.platform.snapshot.json
```

**Comment by arpanchakra29** [comment]
@david-leifker  can you please rerun the failed step , looks like some timeout happened

**Comment by maggiehays** [comment]
@coderabbitai summary

**Pull request merged**
