### PR TITLE
feat(ingest/snowflake): allow iceberg tables in lineage and access metadata

### PR DESCRIPTION
**Pull request by alisa-aylward-toast**
## Checklist

- [x] The PR conforms to DataHub's [Contributing Guideline](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [ ] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable). If a new feature has been added a Usage Guide has been added for the same.
- [ ] For any breaking change/potential downtime/deprecation/big changes an entry has been made in [Updating DataHub](https://github.com/datahub-project/datahub/blob/master/docs/how/updating-datahub.md)

Despite not having in their documentation, Iceberg table is a valid object domain in Snowflake access history.  We want to capture this for lineage purposes so any table downstream of an Iceberg table is included in lineage.
Screenshot 2024-07-22 at 8 32 19 AM

## Summary by CodeRabbit

- **New Features**
	- Introduced support for Iceberg tables in Snowflake object handling, expanding the types of objects that can be processed.
	- Updated SQL queries to include Iceberg tables, allowing broader data analysis and processing capabilities.

- **Bug Fixes**
	- Adjusted queries to ensure accurate data retrieval for Iceberg tables alongside existing object types.

### CODE REVIEW

**Comment by alisa-aylward-toast** [comment]
@mayurinehate any feedback on this?

**Review by mayurinehate — APPROVED** [review]
LGTM

**Comment by alisa-aylward-toast** [comment]
@eboneil or @hsheth2 do you know how i could find a maintainer to review?

**Review by hsheth2 — APPROVED** [review]
Sorry about the delay here - we needed to check if there were any side effects that this would have, but I think we're all good

**Pull request merged**
