### PR TITLE
feat(glue): Use table name as human-readable name for Glue ingestion

### PR DESCRIPTION
**Pull request by danielcmessias**
The FQN includes the catalog ID and database name. Add in the 'name' field that is just the table name, like the SQL-based sources, to make it more readable in the UI

Before:
Screenshot 2023-01-31 at 12 15 01

After:
Screenshot 2023-01-31 at 12 16 08

## Checklist

- [x] The PR conforms to DataHub's [Contributing Guideline](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [ ] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable). If a new feature has been added a Usage Guide has been added for the same.
- [ ] For any breaking change/potential downtime/deprecation/big changes an entry has been made in [Updating DataHub](https://github.com/datahub-project/datahub/blob/master/docs/how/updating-datahub.md)

### CODE REVIEW

**Review by hsheth2 — APPROVED** [review]
Code looks good. I suspect some tests will need to be updated as well, but we're ok to merge as long as CI is green.

**Comment by danielcmessias** [comment]
@hsheth2 @jjoyce0510 thanks for looking at this! Seems like the tests passed but the Datahub Jars step failed to do with the `TestSparkJobsLineage` though, which I don't understand. Is this possibly some transient issue with that build step?

**Comment by danielcmessias** [comment]
> Hey @danielcmessias Glue tests are also failing due to current change - https://github.com/datahub-project/datahub/actions/runs/4060755489/jobs/6990676582 You'll need to update glue test golden files for adding the field `name` .

oof didn't scroll down, missed those checks. On it! 👍

**Comment by danielcmessias** [comment]
Re-raising as #7213. Please don't merge master into branches, it makes it a nightmare dealing with rebasing! 😅

**Comment by hsheth2** [comment]
@danielcmessias ah my bad - sorry about that

**Pull request closed without merging**
