### PR TITLE
feat(config): support alternate hashing algorithm for doc id

### PR DESCRIPTION
**Pull request by pinakipb2**
Vulnerability was introduced because of using MD5. So now the hasing algorithm comes from an env variable.

And can be replaced with SHA-256 followed by migrations.

## Summary by CodeRabbit

- **New Features**
  - Added support for dynamic hash algorithm selection for document ID generation in ElasticSearch.
  - Introduced `ELASTIC_ID_HASH_ALGO` environment variable to specify the hash algorithm (default `MD5`).

- **Configuration**
  - Updated various environment files and `application.yaml` to include `ELASTIC_ID_HASH_ALGO`, defaulting to `MD5`.

- **Tests**
  - Enhanced test configurations to specify the ID hash algorithm as `MD5` during test execution.

### CODE REVIEW

**Review by david-leifker — APPROVED** [review]
LGTM! The hashing of the document ids is not technically a vulnerability, they are not used in any cryptographic process or anything besides generating unique document ids.

**Comment by david-leifker** [comment]
Once I can get the tests run and it looks good, then we'll get it merged.

**Review by jjoyce0510 — COMMENTED** [review]
It looks like these changes need to be reflected in datahub-quickstart YAML files as well

**Comment by RyanHolstien** [comment]
This is not a vulnerability and should only be changed _on brand new deployments that have never had any ingests and in general with caution_. I don't really think this is something we should support. Changing this configuration on a deployed instance will result in orphaning all currently created edges without an appropriate migration script. The usage of MD5 here is in line with its recommended use cases, all we care about here is hash collisions which MD5 is sufficiently low in probability.

**Comment by david-leifker** [comment]
Updating branch to run CI again, checking for test failures again.

**Comment by david-leifker** [comment]
There are currently CI test failures on this branch which prevents merging into master at this time. Missing import most likely [here](https://github.com/datahub-project/datahub/actions/runs/10181832571/job/28162974575?pr=10423#step:7:1617) for example.

**Comment by david-leifker** [comment]
Seeing some failures in CI with regard to the algorithm being null, i.e. https://github.com/datahub-project/datahub/actions/runs/10187240058/job/28182260173?pr=10423#step:6:13305

This should be reproduce-able locally by `./gradlew :metadata-io:test`

**Comment by pinakipb2** [comment]
> Seeing some failures in CI with regard to the algorithm being null, i.e. https://github.com/datahub-project/datahub/actions/runs/10187240058/job/28182260173?pr=10423#step:6:13305
> 
> This should be reproduce-able locally by `./gradlew :metadata-io:test`

Updated the PR and the build is not failing on that.

**Comment by david-leifker** [comment]
I think there are likely missing changes to the quickstart docker compose. This is likely breaking the smoke tests. Please run this command from the logs [here](https://github.com/datahub-project/datahub/actions/runs/10235730861/job/28316926029?pr=10423#step:4:73). It will likely update some files in the `docker/quickstart` directory and fix the failing smoke tests.

**Comment by pinakipb2** [comment]
@david-leifker - All checks passed. Thanks a lot for the help !!

**Comment by david-leifker** [comment]
Nice! Thank you!

**Pull request merged**
