### PR TITLE
feat(ingest): profiling - allow/deny SQL columns by type

### PR DESCRIPTION
**Pull request by kevinhu**
## Checklist
- [x] The PR conforms to DataHub's [Contributing Guideline](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [x] Tests for the changes have been added/updated (if applicable)
- [x] Docs related to the changes have been added/updated (if applicable)

### CODE REVIEW

**Comment by rumbin** [comment]
Eagerly waiting for this PR :-)

**Comment by shirshanka** [comment]
Will re-review this after automatic ingestion doc generation is finished.

**Comment by karoliskascenas** [comment]
Any chance this gets merged?

**Comment by jjoyce0510** [comment]
Folks - we are picking this PR up as Kevin is no longer maintaining it.

We realize this is something that various folks want!

Thanks
John

cc @aseembansal-gogo @rslanka

**Comment by jjoyce0510** [comment]
Hi folks. We are looking for community volunteers to take forward this PR. Acryl Core team has decided to de-prioritize this work. That being said, we'd be happy to accept a contrib.

- John

**Pull request closed without merging**
