### PR TITLE
fix(gms): GMS hang when upgrade image #8270

### PR DESCRIPTION
**Pull request by yangjiandan**
## Checklist

- [ ] The PR conforms to DataHub's [Contributing Guideline](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [ ] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable). If a new feature has been added a Usage Guide has been added for the same.
- [ ] For any breaking change/potential downtime/deprecation/big changes an entry has been made in [Updating DataHub](https://github.com/datahub-project/datahub/blob/master/docs/how/updating-datahub.md)

### CODE REVIEW

**Comment by yangjiandan** [comment]
@david-leifker Could you help me review this pr?

**Comment by yangjiandan** [comment]
issue description about this pr is https://github.com/datahub-project/datahub/issues/8270

**Comment by yangjiandan** [comment]
@shirshanka Could you help me review this pr?

**Comment by david-leifker** [comment]
The topic is not intended to expire messages, I don't see any issues with including this, just slightly tweaking the conditional to set the static atomic in case we ever need to refer to that state later. Thanks!

**Review by david-leifker — APPROVED** [review]

**Pull request merged**
