### PR TITLE
feat(graphql): Add sorting option to  single-entity search GraphQL API

### PR DESCRIPTION
**Pull request by Sukeerthi31**
## Checklist

- [x] The PR conforms to DataHub's [Contributing Guideline](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [ ] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable). If a new feature has been added a Usage Guide has been added for the same.
- [ ] For any breaking change/potential downtime/deprecation/big changes an entry has been made in [Updating DataHub](https://github.com/datahub-project/datahub/blob/master/docs/how/updating-datahub.md)

### CODE REVIEW

**Comment by RyanHolstien** [comment]
What's the use case here for using this search path? This function is a likely candidate for deprecation and API calls should utilize searchAcrossEntities which is the main search endpoint our product uses. For a single entity you can specify which entity to search across in searchAcrossEntities if you need it to be targeted.

**Comment by Sukeerthi31** [comment]
> What's the use case here for using this search path? This function is a likely candidate for deprecation and API calls should utilize searchAcrossEntities which is the main search endpoint our product uses. For a single entity you can specify which entity to search across in searchAcrossEntities if you need it to be targeted.

We have some custom pages built that use the search endpoint instead of the searchAcrossEntities. These changes were a part of this PR previously - [Add sorting option to GraphQL search](https://github.com/datahub-project/datahub/pull/3586) , which I have refined based on the current upstream functionalities and tests. Also could you please let us know the reason for the deprecating the single-entity search API.

**Comment by RyanHolstien** [comment]
> > What's the use case here for using this search path? This function is a likely candidate for deprecation and API calls should utilize searchAcrossEntities which is the main search endpoint our product uses. For a single entity you can specify which entity to search across in searchAcrossEntities if you need it to be targeted.
> 
> We have some custom pages built that use the search endpoint instead of the searchAcrossEntities. These changes were a part of this PR previously - [Add sorting option to GraphQL search](https://github.com/datahub-project/datahub/pull/3586) , which I have refined based on the current upstream functionalities and tests. Also could you please let us know the reason for the deprecating the single-entity search API.

It is not really maintained, its functionality is a subset of that provided by searchAcrossEntities and that is the endpoint that continues to receive updates to functionality. We would rather not maintain multiple endpoints with the same functionality.

**Comment by Sukeerthi31** [comment]
> > > What's the use case here for using this search path? This function is a likely candidate for deprecation and API calls should utilize searchAcrossEntities which is the main search endpoint our product uses. For a single entity you can specify which entity to search across in searchAcrossEntities if you need it to be targeted.
> > 
> > 
> > We have some custom pages built that use the search endpoint instead of the searchAcrossEntities. These changes were a part of this PR previously - [Add sorting option to GraphQL search](https://github.com/datahub-project/datahub/pull/3586) , which I have refined based on the current upstream functionalities and tests. Also could you please let us know the reason for the deprecating the single-entity search API.
> 
> It is not really maintained, its functionality is a subset of that provided by searchAcrossEntities and that is the endpoint that continues to receive updates to functionality. We would rather not maintain multiple endpoints with the same functionality.

Alright, that makes sense. Thank you for the clarification, I guess we can close this PR since these changes would anyway be temporary due to deprecation, we can work towards utilising the searchAcrossEntities endpoint across our project for future compatibility with upstream.

**Comment by Sukeerthi31** [comment]
Closing this PR owing to the discussion above

**Pull request closed without merging**
