### PR TITLE
fix(metadata-io): in Neo4j service use proper algorithm to get lineage

### PR DESCRIPTION
**Pull request by lix-mms**
The existing `shortestPath` algorithm supporting the lineage queries has performance issue when the graph database has a high amount of dataset nodes (say >100K). According to Neo4j Cypher PROFILE, it looks like the shortestPath query tries to enumerate all the nodes in the graph database to compute a shortestPath from the start node, which is unnecessary since usually the reachable nodes from the start node are only a very small portion of the whole set of nodes.

Such a performance issue basically leads to that the lineage features in the UI of our DataHub do not work at all. (GraphQL queries `searchAcrossLineage` or `getLineage` always time out, but in the background the execution of the query continues until it finishes after a long time.)

After extensive investigations, we found that [apoc.path.spanningTree](https://neo4j.com/labs/apoc/4.1/overview/apoc.path/apoc.path.spanningTree/) is a better alternative to the existing algorithm. It is uses Breadth-First-Search to expand the lineage paths from the start node, efficiently returns collected paths and does not explore any non-reachable nodes.

With a fix via this PR, in our case, the query time given a node having >200 downstream lineages reduced from ~90s to roughly 1~3s or even less, which is a substantial improvement.

In addition, I restructured how the query statements are formatted, which should lead to better readability and easier maintenance.

## Checklist

- [x] The PR conforms to DataHub's [Contributing Guideline](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [x] ~~Links to related issues (if applicable)~~
- [x] Tests for the changes have been added/updated (if applicable)
- [x] ~~Docs related to the changes have been added/updated (if applicable). If a new feature has been added a Usage Guide has been added for the same.~~
- [x] ~~For any breaking change/potential downtime/deprecation/big changes an entry has been made in [Updating DataHub](https://github.com/datahub-project/datahub/blob/master/docs/how/updating-datahub.md)~~

### CODE REVIEW

**Comment by ghf0128** [comment]
Nice job!

**Comment by lix-mms** [comment]
APOC needs to be enabled in Neo4j for this change to work. In particular, for deployment via _Helm chart_, this PR is needed:
https://github.com/acryldata/datahub-helm/pull/353

The dependency should be communicated via change logs.

**Comment by lix-mms** [comment]
Trying to figure out why `metadata-io:test` is failing. Would be great to have additional support.

**Comment by lix-mms** [comment]
I made a fix and `metadata-io:test` runs successfully now.

(Needed to use neo4j apoc of a slightly higher version to avoid a dependency issue on snakeyaml.)

**Comment by RyanHolstien** [comment]
Can you please make a note of this breaking change in updating-datahub.md? Thanks! Otherwise LGTM :)

**Comment by lix-mms** [comment]
@RyanHolstien Thanks! I'll update it as soon as https://github.com/acryldata/datahub-helm/pull/353 is merged.

Btw, should we also add a breaking change tip line for the replacement of the Neo4j chart (PR: https://github.com/acryldata/datahub-helm/pull/365)? It looks like the existing chart overrides will not automatically work with the new chart structure.

**Comment by lix-mms** [comment]
@RyanHolstien I added a breaking change note to cover this PR change and the change introduced in https://github.com/acryldata/datahub-helm/pull/365. Please check 😋

**Comment by lix-mms** [comment]
Not sure why the build checks start to fail after merging master and the errors do not seem to be relevant to this PR.

Any help is appreciated!

**Comment by lix-mms** [comment]
Only test `cypress_rest` is failing.

**Comment by lix-mms** [comment]
Tests are passing. Mind a final check for merge? 😋 @RyanHolstien

**Review by RyanHolstien — APPROVED** [review]

**Pull request merged**
