### PR TITLE
feat(sdk): dynamically get frontend url from gms

### PR DESCRIPTION
**Pull request by hsheth2**
Also includes ConnectionModel and some improvements to logging.

## Checklist

- [ ] The PR conforms to DataHub's [Contributing Guideline](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [ ] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable). If a new feature has been added a Usage Guide has been added for the same.
- [ ] For any breaking change/potential downtime/deprecation/big changes an entry has been made in [Updating DataHub](https://github.com/datahub-project/datahub/blob/master/docs/how/updating-datahub.md)

### CODE REVIEW

**Review by jjoyce0510 — APPROVED** [review]
LGTM

**Comment by hsheth2** [comment]
CI is failing due to the github outage ;(

**Comment by david-leifker** [comment]
CI doesn't seem like a gha failure here...

**Comment by hsheth2** [comment]
@david-leifker yup this is a real failure - will need to work with @jjoyce0510 to figure out how to fix it.

**Comment by hsheth2** [comment]
Superseded by https://github.com/datahub-project/datahub/issues/10987

**Pull request closed without merging**
