### PR TITLE
feat(ingest): improve tableau lineage, workbooks query, fix pagination

### PR DESCRIPTION
**Pull request by mayurinehate**
Changes:
1. Add support for `platform_instance_map` config to specify platform instance for external tables (e.g. snowflake, hive)
2. Add support for overriding platform name . `lineage_overrides.platform_override_map`
3. Restore pagination change for custom sql and published datasource query, accidently reverted during[ this refractor](https://github.com/datahub-project/datahub/commit/d60f789519479f106a23e91070db530000c19314) [[Issue](https://datahubspace.slack.com/archives/C02GBGG90CU/p1661791092727719?thread_ts=1661788909.119319&cid=C02GBGG90CU)]
4. Emit upstream tables after processing workbooks, embedded datasources, custom SQL tables, published datasources, not to miss emitting external table aspects for any. [[Issue](https://datahubspace.slack.com/archives/C02GBGG90CU/p1661791092727719?thread_ts=1661788909.119319&cid=C02GBGG90CU)]
5. Correct casing for "view" subtype to show "View Definition" tab  [[Issue](https://datahubspace.slack.com/archives/CUMUWQU66/p1658502221337649)]
6. Separate `embeddedDatasourcesConnection` from `workbooksConnection` query to avoid node limit exceeded error for complex workbooks [[Issue](https://datahubspace.slack.com/archives/C02GBGG90CU/p1661791092727719?thread_ts=1661788909.119319&cid=C02GBGG90CU)]

## Checklist
- [x] The PR conforms to DataHub's [Contributing Guideline](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [x] Links to related issues (if applicable)
- [x] Tests for the changes have been added/updated (if applicable)
- [x] Docs related to the changes have been added/updated (if applicable). If a new feature has been added a Usage Guide has been added for the same.
- [ ] For any breaking change/potential downtime/deprecation/big changes an entry has been made in [Updating DataHub](https://github.com/datahub-project/datahub/blob/master/docs/how/updating-datahub.md)

### CODE REVIEW

**Comment by shirshanka** [comment]
Does this PR also address [this](https://datahubspace.slack.com/archives/C02GBGG90CU/p1661791092727719?thread_ts=1661788909.119319&cid=C02GBGG90CU) concern?

**Comment by mayurinehate** [comment]
> Does this PR also address [this](https://datahubspace.slack.com/archives/C02GBGG90CU/p1661791092727719?thread_ts=1661788909.119319&cid=C02GBGG90CU) concern?

Not all of the concerns. Only part where page_size needs to be supported for customSQLTablesConnection and publishedDatasourcesConnection queries.

**Comment by mayurinehate** [comment]
> > Does this PR also address [this](https://datahubspace.slack.com/archives/C02GBGG90CU/p1661791092727719?thread_ts=1661788909.119319&cid=C02GBGG90CU) concern?
> 
> Not all of the concerns. Only part where page_size needs to be supported for customSQLTablesConnection and publishedDatasourcesConnection queries.

All the concerns from [this](https://datahubspace.slack.com/archives/C02GBGG90CU/p1661791092727719?thread_ts=1661788909.119319&cid=C02GBGG90CU) thread are now addressed.

**Comment by cuong-pham** [comment]
@mayurinehate I don't know if we should make this PR bigger. But i observed some behaviour with Tableau Metadata API with regarding CustomSQLTables (we have some very complex custom sql in tableau, that's how i noticed the behaviour):

- If the query is simple enough, `tables` properties in CustomSQLTables actually represents which tables the CustomSQLTable use. Currently we get the `upstreamTables` in `datasouces`, which is not always correct. I can have multiple tables connected to a datasource but my custom query only use one of them, or worse only use the connection to the database.
- If the query is a bit more complex, `tables` will be empty. We have 2 options, using the existing parsing logic (upstreamTables are populated in datasources field) or we can use `sqllineage` to parse the the query, but `sqllineage` is quite buggy.
- The some cases, if the query is too complex, both `tables` and `upstreamTables` in datasources are empty, you have to rely on parsing queries.

I will put some sample payload up

**Review by shirshanka — APPROVED** [review]
LGTM. 
Merging this to make progress and improve this connector. 
We can improve on the cases @cuong-pham mentioned in a future PR.

**Pull request merged**
