### PR TITLE
feat(ingest/s3): support path_specs of different S3 buckets in the same recipe

### PR DESCRIPTION
**Pull request by harsha-mandadi-4026**
## Description
This PR:
- Updates the code to support path specs of different S3 buckets in a recipe
- Cleans up extra new lines etc in some files.

## Checklist

- [x] The PR conforms to DataHub's [Contributing Guideline](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [x] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable). If a new feature has been added a Usage Guide has been added for the same.
- [ ] For any breaking change/potential downtime/deprecation/big changes an entry has been made in [Updating DataHub](https://github.com/datahub-project/datahub/blob/master/docs/how/updating-datahub.md)

### CODE REVIEW

**Comment by harsha-mandadi-4026** [comment]
@hsheth2 - please could you give an approval for the workflows to run?

**Comment by harsha-mandadi-4026** [comment]
Not sure if the failures in the metadata-ingestion 3.7 and 3.10 steps are because of the changes made [here](https://github.com/datahub-project/datahub/commit/26cf0a71ab65dc4ffd71f467ea7eacc472de72a4)

**Review by mayurinehate — APPROVED** [review]
LGTM. 

Apart from mocked integration tests, have you tested this with actual s3 buckets - using different s3 buckets in same recipe ?

**Comment by harsha-mandadi-4026** [comment]
> LGTM.
> 
> Apart from mocked integration tests, have you tested this with actual s3 buckets - using different s3 buckets in same recipe ?

I did try this with the existing behaviour and it didn't support multiple S3 buckets in the same recipe but after removing the check for it, it worked just fine.

**Review by hsheth2 — APPROVED** [review]

**Pull request merged**
