### PR TITLE
feat(model): add searchable annotation to ingestion type so that ingestions can be searched by type as well

### PR DESCRIPTION
**Pull request by jinlintt**
We would like to be able to search ingestions by type through the APIs. It seems harmless to contribute this to the OSS repo.

### CODE REVIEW

**Comment by chriscollins3456** [comment]
> We would like to be able to search ingestions by type through the APIs. It seems harmless to contribute this to the OSS repo.

hey @jinlintt ! what APIs are you hoping to use to query ingestion sources? are you already able to get them by name (as opposed to just by type like you're adding here)?

**Comment by jinlintt** [comment]
> > We would like to be able to search ingestions by type through the APIs. It seems harmless to contribute this to the OSS repo.
> 
> hey @jinlintt ! what APIs are you hoping to use to query ingestion sources? are you already able to get them by name (as opposed to just by type like you're adding here)?

Hey @chriscollins3456, thank you for looking! I was hoping to use the `search` GraphQL API and pass `INGESTION_SOURCE` to the `type` parameter because the doc for `EntityType` includes `INGESTION_SOURCE`.

But it doesn't seem to work.
```
java.lang.IllegalArgumentException: Unknown entity type: INGESTION_SOURCE at com.linkedin.datahub.graphql.resolvers.EntityTypeMapper.getName(EntityTypeMapper.java:59)
```

Would adding `INGESTION_SOURCE` to `EntityTypeMapper` be sufficient to make it work?

**Review by jjoyce0510 — APPROVED** [review]

**Comment by jjoyce0510** [comment]
Did not mean to approve this - Making ingestion sources independently searchable would require a bit more work as you've already identified: 

- Add an IngestionSourceType.java class to match other type classes (see for example DomainType.java). 
- Update EntityTypeMapper.java as you've mentioned
- Update UrnToEntityMapper.java

Test!

**Review by jjoyce0510 — CHANGES_REQUESTED** [review]
Add an IngestionSourceType.java class to match other type classes (see for example DomainType.java).
Update EntityTypeMapper.java as you've mentioned
Update UrnToEntityMapper.java

**Pull request closed without merging**
