### PR TITLE
fix(deps): pin snowflake-connector-python

### PR DESCRIPTION
**Pull request by asikowitz**
https://pypi.org/project/snowflake-connector-python/ 3.0.0 states:
> Bumped pyarrow dependency from >=8.0.0,<8.1.0 to >=10.0.1,<10.1.0

However, feast currently limits to <9:
https://github.com/feast-dev/feast/blob/master/setup.py

Tested against acryl snowflake instance with profiling enabled

## Checklist

- [ ] The PR conforms to DataHub's [Contributing Guideline](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [ ] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable). If a new feature has been added a Usage Guide has been added for the same.
- [ ] For any breaking change/potential downtime/deprecation/big changes an entry has been made in [Updating DataHub](https://github.com/datahub-project/datahub/blob/master/docs/how/updating-datahub.md)

### CODE REVIEW

**Review by treff7es — APPROVED** [review]
awesome, thanks!

**Comment by joegoldbeck** [comment]
🤔 curious the reason for this change! i'm running into a dependency resolution issue with `acryl-datahub[snowflake]==0.10.3` and `dbt-snowflake>=1.5.0`. I don't use `feast` so this ends up being blocking the upgrade for me.

is there an issue that arises when this dependency floats? i would naively assume that `pip` would just resolve the dependencies and pick a version of `snowflake-connector-python` that works for both `acryl-datahub` and `feast`, but I'm guessing there's some deeper issue that comes up

**Comment by asikowitz** [comment]
Unfortunately I don't remember the dependency issue that was arising a few months ago. However, we recently removed this constraint when we were able to update feast. The newest release https://github.com/acryldata/datahub/releases/tag/v0.10.3.2 no longer restricts the version of `snowflake-connector-python < 3`

**Comment by joegoldbeck** [comment]
Oh excellent! Thank you @asikowitz for letting me know!! 😄

**Pull request merged**
