### PR TITLE
feat(ingest): upgrade feast

### PR DESCRIPTION
**Pull request by cburroughs**
Upgrade feast from 0.18, which encompasses a variety of api changes summarized at
https://docs.feast.dev/v/v0.25-branch/how-to-guides/automated-feast-upgrade

In addition to the upstream features and bugfixes, this allows rudimentary support for a SnowflakeSource to be enabled and specifying the path of the feature_store config file.

NOTE: `feast apply` was run to regenerate registry.db

## Checklist
- [x] The PR conforms to DataHub's [Contributing Guideline](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [ ] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable). If a new feature has been added a Usage Guide has been added for the same.
- [ ] For any breaking change/potential downtime/deprecation/big changes an entry has been made in [Updating DataHub](https://github.com/datahub-project/datahub/blob/master/docs/how/updating-datahub.md)

### CODE REVIEW

**Comment by cburroughs** [comment]
All of the failing CI jobs appear to be Python 3.7 specific. The minimum version that feast supports is 3.8 so I'm not sure if there is a path forward here.

**Comment by shirshanka** [comment]
seems like you would have the mark the tests as skipped for 3.7, do you know how to accomplish that?

**Comment by cburroughs** [comment]
> seems like you would have the mark the tests as skipped for 3.7, do you know how to accomplish that?

I do not.  if I'm reading the log github log right, the workfows fail on package installation.  So something more than just `@pytest.mark.skipif` would be needed.

**Comment by hsheth2** [comment]
@cburroughs I've tried adding a guard in the setup script and in the pytest - let's see if that makes it through CI

**Review by hsheth2 — APPROVED** [review]
The code looks fine, so we're ok to merge as long as it passes CI

**Comment by cburroughs** [comment]
> @cburroughs I've tried adding a guard in the setup script and in the pytest - let's see if that makes it through CI

Thank you!

**Pull request merged**
