### PR TITLE
feat(openapi): add domain arg

### PR DESCRIPTION
**Pull request by dim-ops**
Add domain arg to OpenApi ingest

## Checklist

- [x] The PR conforms to DataHub's [Contributing Guideline](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [ ] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable). If a new feature has been added a Usage Guide has been added for the same.
- [ ] For any breaking change/potential downtime/deprecation/big changes an entry has been made in [Updating DataHub](https://github.com/datahub-project/datahub/blob/master/docs/how/updating-datahub.md)

### CODE REVIEW

**Review by asikowitz — COMMENTED** [review]
Unfortunately, I believe DataHub [domains](https://datahubproject.io/docs/api/tutorials/domains/#why-would-you-use-domains) are different from what you're trying to ingest here. Can you elaborate on exactly what you're trying to accomplish? Are you trying to ingest all your API's OpenAPI [domains](https://support.smartbear.com/swaggerhub/docs/en/domains.html), or something else?

**Comment by dim-ops** [comment]
> Unfortunately, I believe DataHub [domains](https://datahubproject.io/docs/api/tutorials/domains/#why-would-you-use-domains) are different from what you're trying to ingest here. Can you elaborate on exactly what you're trying to accomplish? Are you trying to ingest all your API's OpenAPI [domains](https://support.smartbear.com/swaggerhub/docs/en/domains.html), or something else?

Yes, I was trying to add the notion of domain to OpenApi as I can do for Glue, Postgres... Because for me, an API can very well be attached to a notion of domain

Example: an API generating data related to advertising should be in the advertising domain.

Don't you agree?

**Review by asikowitz — COMMENTED** [review]
Ah I see, in that case you can use https://datahubproject.io/docs/metadata-ingestion/docs/transformer/dataset_transformer/#pattern-add-dataset-domains, which I believe exactly matches your use case

**Comment by dim-ops** [comment]
don't need my PR? @asikowitz

**Comment by dim-ops** [comment]
Up @asikowitz please 🙏

**Comment by asikowitz** [comment]
Sorry for the radio silence. As this should be possible via transformers, I don't believe we need this PR.

**Pull request closed without merging**
