### PR TITLE
fix: Replace old repository link with new link

### PR DESCRIPTION
**Pull request by kevinneville**
## Checklist
- [x ] The PR conforms to DataHub's [Contributing Guideline](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [ ] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable)

### CODE REVIEW

**Comment by kevinneville** [comment]
@shirshanka I did a lint fix which I think broke the pipeline. Would you mind triggering it again?

**Comment by jjoyce0510** [comment]
You are awesome @kevinneville. Thank you so much for the wonderful contribution!

**Review by jjoyce0510 — APPROVED** [review]
LGTM!

**Comment by kevinneville** [comment]
Thank you!
Not sure what the `gold-star` label means, but feels good to be the first 🥇 

Looking forward to more contributions.

**Pull request merged**
