### PR TITLE
fix(ingest): fixed snowflake oauth ingestion not using role attribute…

### PR DESCRIPTION
**Pull request by daguito81**
… from recipe

## Checklist

- [x] The PR conforms to DataHub's [Contributing Guideline](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [x] Links to related issues (if applicable)
- [ ] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable). If a new feature has been added a Usage Guide has been added for the same.
- [ ] For any breaking change/potential downtime/deprecation/big changes an entry has been made in [Updating DataHub](https://github.com/datahub-project/datahub/blob/master/docs/how/updating-datahub.md)

### CODE REVIEW

**Comment by daguito81** [comment]
Solves Issue #6825

**Review by jjoyce0510 — APPROVED** [review]
This LGTM. Thank you!

**Review by jjoyce0510 — APPROVED** [review]

**Comment by daguito81** [comment]
Resynced branch with master and it retrigger the CICD. However, before approving them to run again I had some questions regarding the results of the original test run. 2 errors were linting errors in files that I'm not touching and AFAIK my changes shouldn't change that behaviour. The added line would just affect the snowflake connection method call. 
The other error was the smoke-tests and from the error it seemed like the process didn't quite start fast enough. Would love some feedback regarding this.

**Comment by mayurinehate** [comment]
Closes #6824

**Pull request merged**
