### PR TITLE
fix(ci): skip publish step on PRs from forks

### PR DESCRIPTION
**Pull request by hsheth2**
Fixes a subtle regression from https://github.com/datahub-project/datahub/pull/8515.

## Checklist

- [ ] The PR conforms to DataHub's [Contributing Guideline](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [ ] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable). If a new feature has been added a Usage Guide has been added for the same.
- [ ] For any breaking change/potential downtime/deprecation/big changes an entry has been made in [Updating DataHub](https://github.com/datahub-project/datahub/blob/master/docs/how/updating-datahub.md)

### CODE REVIEW

**Review by asikowitz — APPROVED** [review]

**Comment by asikowitz** [comment]
Seems like we have another check with different logic:
```
        if: ${{ needs.setup.outputs.publish != 'true' }}
```
and we go back and forth on which we use... should prob be consistent here

**Comment by hsheth2** [comment]
@asikowitz lets see if this tweak does the trick

**Comment by asikowitz** [comment]
Doesn't look like it

**Comment by anshbansal** [comment]
https://github.com/datahub-project/datahub/pull/8677 should supersede this

**Pull request closed without merging**
