### PR TITLE
feat(ingest): Add Source from Vertica

### PR DESCRIPTION
**Pull request by eburairu**
Adding a Metadata Ingestion Source Guide: 
- [x] 1. Set up the configuration model
- [ ] 2. Set up the reporter
- [x] 3. Implement the source itself
  - [x] add get_view_definition 
  - [x] add get_column
  - [x] support DATE column type
  - [x] support TIMESTAMP column type
  - [x] support UUID column type
- [x] 4. Set up the dependencies
- [x] 5. Enable discoverability
- [ ] 6. Write tests
  - [ ] unit test
  - [ ] integration test
- [ ] 7. Write docs
- [x] 8. Add SQL Alchemy mapping (if applicable)
- [ ] 9. Add logo

## Checklist
- [x] The PR conforms to DataHub's [Contributing Guideline](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [ ] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable). If a new feature has been added a Usage Guide has been added for the same.

### CODE REVIEW

**Comment by eburairu** [comment]
Errors regarding TIMESTAMP and DATE types have been resolved. 👏 

### Regarding the TIMESTAMP type error

It seems that the function could not be called due to the timezone argument defined within sqlalchemy_vertica.
The error is avoided by defining new `def TIMESTAMP_WITH_TIMEZONE` and `def TIME_WITH_TIMEZONE`.

The following is a reference: 
https://github.com/alexryndin/sqlalchemy-vertica/commit/9612580071fc85e79f272d670bc9c552fddf2b19

### Regarding the DATE type error

I changed it so that args = () for DATE type, since we cannot pass arguments to DATE type.

**Comment by eburairu** [comment]
Should I create a new branch and merge into it instead of the main branch?

**Review by rslanka — APPROVED** [review]
LGTM!

**Comment by njalan** [comment]
When this feature will be released on new version?

**Pull request merged**
