### PR TITLE
feat(ingest/glue): Include environment on container guid key of container URN

### PR DESCRIPTION
**Pull request by siladitya2**
## Checklist
We are currently excluding `environment` while generating the GUID key for `container` `urn`.
This PR introducing a configurable option `include_env_on_container_key` which can be used if user wish to consider `environment` as well along with `instance` while generating the GUID of a `container` `urn` to avoid collision for same `instance` and different `environment`.

PR changes include:
1. A new config flag `include_env_on_container_key` is added, if it is set to `True` then `env` will be included to generate container GUID key along with platform `instance`.

2. Updated Glue connector code to use the `include_env_on_container_key` to generate `container` guid key.

- [ ] The PR conforms to DataHub's [Contributing Guideline](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [ ] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable). If a new feature has been added a Usage Guide has been added for the same.
- [ ] For any breaking change/potential downtime/deprecation/big changes an entry has been made in [Updating DataHub](https://github.com/datahub-project/datahub/blob/master/docs/how/updating-datahub.md)

### CODE REVIEW

**Comment by sid-acryl** [comment]
@hsheth2 
The env is deprecated and we are prompting to use platform-instance instead of env, however this PR is introducing the env in container key generation, so I am not sure if we want to go ahead with the PR. 

Need your input on this PR

**Review by hsheth2 — COMMENTED** [review]
I would like to understand the motivation here a bit more first - do you have two Glue setups with the same platform and platform instance, and only distinguished by env?

Given that platform instances are supposed to be uniquely identified by the platform + instance name, I'm not certain this change makes sense.

**Comment by hsheth2** [comment]
@sgomezvillamor that makes a ton of sense. We recently did something similar for datajobs/dataflows https://github.com/datahub-project/datahub/pull/10814

**Comment by sgomezvillamor** [comment]
> @sgomezvillamor that makes a ton of sense. We recently did something similar for datajobs/dataflows #10814

I see. That would require to add the `env` property to the _eg_ container properties aspect.

```
  /**
   * Environment for this job
   */
  @Searchable = {
    "fieldType": "KEYWORD",
    "addToFilters": true,
    "filterNameOverride": "Environment",
    "queryByDefault": false
  }
  env: optional FabricType
```

**Pull request closed without merging**
