### PR TITLE
feat(ingest): enable container stateful ingestion

### PR DESCRIPTION
**Pull request by wangsaisai**
## Checklist

- [x] The PR conforms to DataHub's [Contributing Guideline](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [x] Links to related issues (if applicable)
- [x] Tests for the changes have been added/updated (if applicable)
- [x] Docs related to the changes have been added/updated (if applicable). If a new feature has been added a Usage Guide has been added for the same.
- [x] For any breaking change/potential downtime/deprecation/big changes an entry has been made in [Updating DataHub](https://github.com/datahub-project/datahub/blob/master/docs/how/updating-datahub.md)

### CODE REVIEW

**Review by treff7es — APPROVED** [review]
lgtm, thanks for the contribution

**Review by treff7es — CHANGES_REQUESTED** [review]
@wangsaisai please, can you run black formatting on sql_common.py? 
It seems our formatting change fails.

**Comment by wangsaisai** [comment]
@treff7es after black formatting sql_common.py, will modify codes contribute by others. Just format my owner code or format total file?

**Comment by treff7es** [comment]
> @treff7es after black formatting sql_common.py, will modify codes contribute by others. Just format my owner code or format total file?

Black formatting is a requirement for every pr, so the black formatting on the file would only change your code.

**Comment by wangsaisai** [comment]
@treff7es  please help review again. Thanks

**Review by treff7es — APPROVED** [review]
lgtm, thanks for the contribution!

**Pull request merged**
