### PR TITLE
build(elasticsearch): updates elasticsearch client version to enable …

### PR DESCRIPTION
**Pull request by nmbryant**
Optum has switched to Elasticsearch 8, and as a result we were seeing 'Error feeding bulk request' in the mae-consumer. However, there was always 200 OK in these error messages, so it appeared that everything was working just that the mae-consumer wasn't able to determine if elasticsearch requests were successful. 

To fix this issue, we have enabled compatibility mode in the elasticsearch client, which required upgrading the client to a newer version (7.17.1). We have deployed and tested the changes in this PR in one of our lower environments, now the mae-consumer no longer has these errors and everything is else is also working properly. However we only deployed these changes in one of our lower environments last Friday, so may want to give us some more time to further validate that these changes have no issues before merging to main.

Other than that mae-consumer error log we haven't seen any other issues with switching to Elasticsearch 8.

## Checklist

- [x] The PR conforms to DataHub's [Contributing Guideline](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [x] Links to related issues (if applicable)
- [x] Tests for the changes have been added/updated (if applicable)
- [x] Docs related to the changes have been added/updated (if applicable). If a new feature has been added a Usage Guide has been added for the same.
- [x] For any breaking change/potential downtime/deprecation/big changes an entry has been made in [Updating DataHub](https://github.com/datahub-project/datahub/blob/master/docs/how/updating-datahub.md)

### CODE REVIEW

**Comment by RyanHolstien** [comment]
Not sure if we can accept this due to the license change with 7.11. https://www.elastic.co/pricing/faq/licensing 7.17 is published under SSPL which is copy-left.

**Comment by nmbryant** [comment]
Ah sorry, I wasn't aware of that license change. Unfortunately, the [compatibility mode](https://www.elastic.co/guide/en/elasticsearch/client/java-rest/current/java-rest-high-compatibility.html) function was added in 7.16, so this PR could probably be closed if the license change is an issue.

**Comment by tkdrahn** [comment]
Im not 100% sure but it seems like the HLRC on its own is  exempt from the SSPL license? https://www.elastic.co/pricing/faq/licensing#elasticsearch-api-how-affect-me

**Comment by RyanHolstien** [comment]
The HLRC is licensed under the Elastic License (also not an Open Source license): 
`The Java HLRC has dependencies on the core of Elasticsearch, and as a result this client library will be licensed under the Elastic License`

https://github.com/elastic/elasticsearch/blob/v7.17.1/client/rest-high-level/src/main/resources/forbidden/rest-high-level-signatures.txt

We'll have to update to the new Java API Client to avoid this which will require a decent chunk of dev work and testing to make sure it doesn't have compatibility issues with versions of Elastic & OpenSearch community members are running.

**Comment by RyanHolstien** [comment]
Basically it would put us at the mercy of Elastic.co's discrepancy to consider derivative works using the library, which it seems their current stance is:

`we do not consider using the Java HLRC as a client library in development of an application or library used to access Elasticsearch to constitute a derivative work under the Elastic License, and this will not have any impact on how you license the source code of your application using this client library or how you distribute it.`

but the license itself provides no guarantees of that stance. It would have to be upheld by legal precedent, which feels a bit risky. IANAL though.

**Comment by tkdrahn** [comment]
Sorry forgot to respond to this. Yes that makes sense you can’t risk ES changing their mind on when to enforce license.

Also agree that migrating to Java API Client seems to be the best path forward, although not a small change as you mentioned

**Comment by rtekal** [comment]
A week ago there was an announcement from Elastic about License and thought of adding it here:

https://ir.elastic.co/news/news-details/2024/Elastic-Announces-Open-Source-License-for-Elasticsearch-and-Kibana-Source-Code/default.aspx

**Pull request closed without merging**
