### PR TITLE
chore(ui): change background color to transparent for avatar with photoUrl

### LINKED ISSUE #7145: Minor: User Profile Image can have colored background
**Describe the bug**

Based on this Slack thread: https://datahubspace.slack.com/archives/CV2UXSE9L/p1674716341745369

When a user uploads a profile image with a transparent background, we will see the underlying default color behind the image. 
This is a minor issue but a great first issue.

### PR DESCRIPTION
**Pull request by hieunt-itfoss**
Resolves #7145

- Custom AvatarStyled: add `transparent` props if the avatar doesn't have background-color which is interpolated in `getAvatarColor`.
- Remove background-color of the avatar with photoUrl.

## Checklist

- [x] The PR conforms to DataHub's [Contributing Guideline](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [x] Links to related issues (if applicable)
- [ ] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable). If a new feature has been added a Usage Guide has been added for the same.
- [ ] For any breaking change/potential downtime/deprecation/big changes an entry has been made in [Updating DataHub](https://github.com/datahub-project/datahub/blob/master/docs/how/updating-datahub.md)

### CODE REVIEW

**Review by aditya-radhakrishnan — COMMENTED** [review]
Thank you for making this change! Could you post before and after screenshots before I approve?

**Comment by jjoyce0510** [comment]
Looks like linting is failing! Do you mind checking?

**Comment by hieunt-itfoss** [comment]
> Looks like linting is failing! Do you mind checking?

Sorry for the late response. I just update this PR. The linting is fixed.

**Comment by hieunt-itfoss** [comment]
@aditya-radhakrishnan 

Before:
Screen Shot 2023-03-23 at 5 17 51 PM

After removing background:
Screen Shot 2023-03-23 at 5 18 10 PM

**Comment by aditya-radhakrishnan** [comment]
Can you post another set of screenshots confirming that for Avatars without a photo, this works as expected?

**Comment by hieunt-itfoss** [comment]
> Can you post another set of screenshots confirming that for Avatars without a photo, this works as expected?

avatarWithDefault: 
Screen Shot 2023-04-20 at 6 09 26 PM
avatarWithInitial (name):
Screen Shot 2023-04-20 at 6 24 49 PM

**Review by chriscollins3456 — APPROVED** [review]
looks great! thanks for this

**Pull request merged**
