### PR TITLE
feat(elasticsearch): Add nested type display

### PR DESCRIPTION
**Pull request by liyuhui666**
Add nested type display  in ES data source

## Checklist
- [ ] The PR conforms to DataHub's [Contributing Guideline](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [ ] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable). If a new feature has been added a Usage Guide has been added for the same.
- [ ] For any breaking change/potential downtime/deprecation/big changes an entry has been made in [Updating DataHub](https://github.com/datahub-project/datahub/blob/master/docs/how/updating-datahub.md)

### CODE REVIEW

**Comment by liyuhui666** [comment]
image

**Comment by liyuhui666** [comment]
image

**Comment by rslanka** [comment]
Hi @liyuhui666, I have taken a closer look at the change and this is more of a UI bug than the field paths themselves. While this change is fixing things up in the UI, it will alter the field paths for existing deployments as field path is a primary key for a field and hence loss of any existing data on them. Let's hold off on merging this.
cc: @gabe-lyons, @shirshanka

**Review by rslanka — APPROVED** [review]
LGTM!

**Comment by yuduoyu98** [comment]
Why remove `elastic_type != 'nested'` ?

**Pull request merged**
