### PR TITLE
build(ingest): Bump avro pin: security vulnerability

### PR DESCRIPTION
**Pull request by asikowitz**
Unit tests looked good locally

## Checklist

- [ ] The PR conforms to DataHub's [Contributing Guideline](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [ ] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable). If a new feature has been added a Usage Guide has been added for the same.
- [ ] For any breaking change/potential downtime/deprecation/big changes an entry has been made in [Updating DataHub](https://github.com/datahub-project/datahub/blob/master/docs/how/updating-datahub.md)

### CODE REVIEW

**Comment by asikowitz** [comment]
Ran tests but not lint :|

**Comment by hsheth2** [comment]
@asikowitz looks like it's running into issues with the avro schema translation

**Comment by asikowitz** [comment]
The avro library added type annotations lol, I think that's it

**Review by hsheth2 — APPROVED** [review]
lgtm once ci passes

**Comment by asikowitz** [comment]
@hsheth2 I added `# mypy: ignore errors` to the top of `_schema_classes.py` to pass CI. Please confirm this sounds reasonable to you

**Review by hsheth2 — APPROVED** [review]

**Pull request merged**
