### PR TITLE
Update  schema-registry  docker.env

### PR DESCRIPTION
**Pull request by liyuhui666**
When we want to connect to Kerberos kafka, we need to add some new parameters and copy jaas.conf, krb5.conf and other configuration files to the schema-registry container

## Checklist
- [ ] The PR conforms to DataHub's [Contributing Guideline](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [ ] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable). If a new feature has been added a Usage Guide has been added for the same.
- [ ] For any breaking change/potential downtime/deprecation/big changes an entry has been made in [Updating DataHub](https://github.com/datahub-project/datahub/blob/master/docs/how/updating-datahub.md)

### CODE REVIEW

**Comment by jjoyce0510** [comment]
Hi @liyuhui666!

Thanks for the contribution. What is the intention of the PR? I see that we are only changing the default environment variables? 

John

**Comment by liyuhui666** [comment]
Hi John！
When we want to modify the environment variables to support The Kerberos schema, we can only look at the schema-Registry code without prompting which environment variables are available, which is inconvenient. We add environment variables that can later be used in the docker-compose file
Li

**Comment by jjoyce0510** [comment]
This makes sense - do you mind commenting the new environment variables out? I want to make sure we don't break any existing deployments of datahub quickstart!

For example, 

```
# Uncomment to customize the Schema Registry kafka store connection 
# SCHEMA_REGISTRY_KAFKASTORE_SECURITY_PROTOCOL=PLAINTEXT
# SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS=broker:29092
# ZOOKEEPER_SASL_ENABLED=false
# KAFKA_OPTS=-Xms1g -Xmx1g 
# SCHEMA_REGISTRY_JMX_OPTS=-Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false
```

**Comment by liyuhui666** [comment]
You're right. We should comment it out as a reminder

**Review by jjoyce0510 — APPROVED** [review]

**Pull request merged**
