### PR TITLE
fix(logout-oidc): retrieve OIDC URL from env var and logout properly

### PR DESCRIPTION
**Pull request by luizhsalazar**
## Checklist

- [X] The PR conforms to DataHub's [Contributing Guideline](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [X] Links to related issues (if applicable)
- [X] Tests for the changes have been added/updated (if applicable)
- [X] Docs related to the changes have been added/updated (if applicable). If a new feature has been added a Usage Guide has been added for the same.
- [X] For any breaking change/potential downtime/deprecation/big changes an entry has been made in [Updating DataHub](https://github.com/datahub-project/datahub/blob/master/docs/how/updating-datahub.md)

### CODE REVIEW

**Review by david-leifker — APPROVED** [review]

**Comment by david-leifker** [comment]
@luizhsalazar - FYI the changes here prevent the frontend from starting during CI smoke-tests.

**Review by david-leifker — CHANGES_REQUESTED** [review]
Fix frontend startup issue

**Comment by david-leifker** [comment]
I believe these were addressed in these PRs
https://github.com/datahub-project/datahub/pull/11709
https://github.com/datahub-project/datahub/pull/11878

**Comment by rafaelsmf** [comment]
Still an issue, tested on 0.14.1

**Comment by david-leifker** [comment]
PRs above would be in `v0.15.0rcX` at the earliest

**Pull request closed without merging**
