### PR TITLE
add http authorization elasticsearch

### PR DESCRIPTION
**Pull request by cateto**
## Checklist
- [x] The PR conforms to DataHub's [Contributing Guideline](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [ ] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable). If a new feature has been added a Usage Guide has been added for the same.
- [ ] For any breaking change/potential downtime/deprecation/big changes an entry has been made in [Updating DataHub](https://github.com/datahub-project/datahub/blob/master/docs/how/updating-datahub.md)

### CODE REVIEW

**Comment by RyanHolstien** [comment]
Hey @cateto , can you fix the checkstyle violations happening for the PR?

**Comment by cateto** [comment]
@RyanHolstien I fix it

**Comment by RyanHolstien** [comment]
@shirshanka Need workflow approval

**Review by RyanHolstien — APPROVED** [review]
Changes lgtm, disclaimer that this exposes user/password over clear http, but I don't think this is an issue unless a server gets misconfigured.

**Comment by shirshanka** [comment]
@cateto : there seems to be a checkstyle error still. 

You can fix it like this:
```diff
diff --git a/metadata-service/factories/src/main/java/com/linkedin/gms/factory/common/RestHighLevelClientFactory.java b/metadata-service/factories/src/main/java/com/linkedin/gms/factory/common/RestHighLevelClientFactory.java
index a5ae9b8017..463b216b5b 100644
--- a/metadata-service/factories/src/main/java/com/linkedin/gms/factory/common/RestHighLevelClientFactory.java
+++ b/metadata-service/factories/src/main/java/com/linkedin/gms/factory/common/RestHighLevelClientFactory.java
@@ -94,8 +94,7 @@ public class RestHighLevelClientFactory {

     if (username != null && password != null) {
       StringJoiner stringJoiner = new StringJoiner(":").add(username).add(password);
-      String CREDENTIALS_STRING = stringJoiner.toString();
-      String encodedBytes = Base64.getEncoder().encodeToString(CREDENTIALS_STRING.getBytes());
+      String encodedBytes = Base64.getEncoder().encodeToString(stringJoiner.toString().getBytes());
       Header[] authHeaders = {new BasicHeader("Authorization", "Basic " + encodedBytes)};
       builder.setDefaultHeaders(authHeaders);
     }
```

**Comment by jjoyce0510** [comment]
Running checks. Will merge once we pass.

**Comment by jjoyce0510** [comment]
As per @dexter-mh-lee's comment - we should have a way to achieve this already. Going to close do to duplication.

@cateto Please feel free to reopen / ping us on Slack if you think this is a mistake!~

**Comment by jjoyce0510** [comment]
For reference: This file now supports username / password auth via http (and https): https://github.com/datahub-project/datahub/blob/master/metadata-service/factories/src/main/java/com/linkedin/gms/factory/common/RestHighLevelClientFactory.java

**Pull request closed without merging**
