### PR TITLE
feat(ingest/bigquery): Add schema metadata field for _PARTITIONTIME internal column

### PR DESCRIPTION
**Pull request by asikowitz**
Produces the following smoke test change:

```
Urn changed, urn:li:dataset:(urn:li:dataPlatform:bigquery,acryl-staging-2.smoke_test_db_4.table_with_ingestion_time_partition,PROD):
<schemaMetadata> changed:
	Item aspect['fields'][1] added to iterable.
Old aspect:
    schemaName: acryl-staging-2.smoke_test_db_4.table_with_ingestion_time_partition
    platform: urn:li:dataPlatform:bigquery
    version: 0
    created:
      time: 0
      actor: urn:li:corpuser:unknown
    lastModified:
      time: 0
      actor: urn:li:corpuser:unknown
    hash: ''
    platformSchema:
      com.linkedin.schema.MySqlDDL:
        tableSchema: ''
    fields:
    - fieldPath: transaction_id
      nullable: true
      type:
        type:
          com.linkedin.schema.NumberType: {}
      nativeDataType: INT64
      recursive: false
      globalTags:
        tags: []
      isPartOfKey: false
New aspect:
    schemaName: acryl-staging-2.smoke_test_db_4.table_with_ingestion_time_partition
    platform: urn:li:dataPlatform:bigquery
    version: 0
    created:
      time: 0
      actor: urn:li:corpuser:unknown
    lastModified:
      time: 0
      actor: urn:li:corpuser:unknown
    hash: ''
    platformSchema:
      com.linkedin.schema.MySqlDDL:
        tableSchema: ''
    fields:
    - fieldPath: transaction_id
      nullable: true
      type:
        type:
          com.linkedin.schema.NumberType: {}
      nativeDataType: INT64
      recursive: false
      globalTags:
        tags: []
      isPartOfKey: false
    - fieldPath: _PARTITIONTIME
      nullable: true
      type:
        type:
          com.linkedin.schema.TimeType: {}
      nativeDataType: TIMESTAMP
      recursive: false
      globalTags:
        tags:
        - tag: urn:li:tag:PARTITION_KEY
      isPartOfKey: false
```

## Checklist

- [ ] The PR conforms to DataHub's [Contributing Guideline](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [ ] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable). If a new feature has been added a Usage Guide has been added for the same.
- [ ] For any breaking change/potential downtime/deprecation/big changes an entry has been made in [Updating DataHub](https://github.com/datahub-project/datahub/blob/master/docs/how/updating-datahub.md)

## Summary by CodeRabbit

- **New Features**
	- Improved BigQuery integration by adding logic to handle partition information for tables, including appending a timestamp column to schema metadata under specific conditions.

### CODE REVIEW

**Review by treff7es — APPROVED** [review]
lgtm

**Comment by hsheth2** [comment]
For the partition key tag, let's link to https://cloud.google.com/bigquery/docs/querying-partitioned-tables in the docs for that tag

**Review by hsheth2 — CHANGES_REQUESTED** [review]
This requires a few tweaks now that the SchemaField.isPartitioningKey field is actually respected by the UI

**Comment by asikowitz** [comment]
Closing as this is old and stale

**Pull request closed without merging**
