### PR TITLE
Draft(metadata-ingestion): Draft delta lake ingestion via delta sharing

### PR DESCRIPTION
**Pull request by buggythepirate**
## Checklist
- [x] The PR conforms to DataHub's [Contributing Guideline](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [x] Tests for the changes have been added/updated (if applicable)
- [x] Docs related to the changes have been added/updated (if applicable). If a new feature has been added a Usage Guide has been added for the same.
- [ ] For any breaking change/potential downtime/deprecation/big changes an entry has been made in [Updating DataHub](https://github.com/datahub-project/datahub/blob/master/docs/how/updating-datahub.md)

### CODE REVIEW

**Comment by jjoyce0510** [comment]
@buggythepirate Hi there! Are you still working on this PR? If not we will consider closing due to inactivity.

Thanks
John

**Comment by buggythepirate** [comment]
Hi @jjoyce0510 

A little combination of me waiting for feedback from you guys and then getting buried completely in work. 😭 

Is there still interest? Then I can work on it and get it ready within 2 weeks.

**Comment by jjoyce0510** [comment]
Hi @buggythepirate - We are still interested but we have since added a delta-lake and hana connectors. Is there any interest in merging this code into the existing connectors?

We'd love to support you further here, but waiting for response before more action.

Thanks
- John

**Comment by jjoyce0510** [comment]
Hi there! I've not heard back yet. I'm closing this PR due to inactivity. Please feel free to reopen once you're back!

**Pull request closed without merging**
