### PR TITLE
feat(ingestion): optionally disable some kafka schema warnings

### PR DESCRIPTION
**Pull request by claudio-benfatto**
Hi community, I was having a look at the the kafka connector code these days in order to add stateful ingestion to it and I noticed that there are two cases that produce warnings:

- [Value Schema not found](https://github.com/linkedin/datahub/blob/master/metadata-ingestion/src/datahub/ingestion/source/kafka.py#L165-L166)
- [Key/Value Schema is not AVRO](https://github.com/linkedin/datahub/blob/master/metadata-ingestion/src/datahub/ingestion/source/kafka.py#L175-L177)

while in some very specific scenarios this behaviour could be useful, both of these warnings could actually be misleading, as outcome of perfectly normal situations (i.e. a topic with no schema or using a different schema strategy and a topic with a non AVRO schema), especially when stateful ingestion is active and a commit policy of `ON_NO_ERRORS_AND_NO_WARNINGS` is selected.

My proposal is to add a couple of configuration parameters to the source:
- `ignore_warnings_on_missing_schema`
- `ignore_warnings_on_schema_type`

to optionally disable reporting the warnings.

## Checklist
- [x] The PR conforms to DataHub's [Contributing Guideline](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/linkedin/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [x] Tests for the changes have been added/updated (if applicable)
- [x] Docs related to the changes have been added/updated (if applicable)

### CODE REVIEW

**Comment by shirshanka** [comment]
@rslanka : Could you take a look at this?

**Comment by shirshanka** [comment]
@claudio-benfatto: don't fret! @rslanka will be helping you merge this with the latest changes for non-default subject-name strategies.

**Comment by claudio-benfatto** [comment]
> @claudio-benfatto: don't fret! @rslanka will be helping you merge this with the latest changes for non-default subject-name strategies.

hi @shirshanka @rslanka no worries, actually we are quite happy you added this feature.

Examining the code I noticed that now we try to extract the schemas only for topics for which there is a subject, so one of the original cases, `ignore_warnings_on_missing_schema` doesn't seem necessary anymore and I removed it.

I just kept the `ignore_warnings_on_schema_type` flag that is still relevant in case of non-AVRO schemas

**Review by rslanka — APPROVED** [review]
LGTM!

**Pull request merged**
