### PR TITLE
fix(ingest): drop empty fields

### PR DESCRIPTION
**Pull request by anshbansal**
## Checklist

- [ ] The PR conforms to DataHub's [Contributing Guideline](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [ ] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable). If a new feature has been added a Usage Guide has been added for the same.
- [ ] For any breaking change/potential downtime/deprecation/big changes an entry has been made in [Updating DataHub](https://github.com/datahub-project/datahub/blob/master/docs/how/updating-datahub.md)

### CODE REVIEW

**Review by hsheth2 — APPROVED** [review]
might've been better to rename auto_fix_duplicate_schema_field_paths -> auto_fix_schema_field_paths, and put this functionality in the same method

**Comment by anshbansal** [comment]
airflow failure is being fixed here https://github.com/datahub-project/datahub/pull/11616

**Comment by anshbansal** [comment]
`testQuick` passed but it is stuck for some reason. Happening in multiple PRs
- https://github.com/datahub-project/datahub/pull/11578
- https://github.com/datahub-project/datahub/pull/11607

So merging as not related to this PR

**Comment by tkdrahn** [comment]
I don’t believe we have that pulled into our ingestion code, will take a look. 

It looks like that will just drop the field completely from the Schema, that’s not what we want either is it?

**Comment by hsheth2** [comment]
I’d like to understand the empty column name thing - we had assume that that wasn’t really a valid thing (and it also messes up our UI)

What’s the use case for it - eg how do you query a table/view with an empty column name?

**Comment by tkdrahn** [comment]
I certainly wouldn’t do it but our catalog team doesn’t own the data sets we’re trying to ingest. We have a large number of Snowflake views at our company that have a column with a blank column name

here is an example Snowflake SQL to demonstrate:

create view example_view as ( select field1 as “”, field2 as “field2” from my_base_table);

select * from example_view where “” = ‘some value’;

**Pull request merged**
