### PR TITLE
fix: OBS-729 | Filters: Fix alignment on nested dropdown

### PR DESCRIPTION
**Pull request by sumitappt**
## Checklist

- [ ] The PR conforms to DataHub's [Contributing Guideline](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [ ] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable). If a new feature has been added a Usage Guide has been added for the same.
- [ ] For any breaking change/potential downtime/deprecation/big changes an entry has been made in [Updating DataHub](https://github.com/datahub-project/datahub/blob/master/docs/how/updating-datahub.md)

### CODE REVIEW

**Comment by sumitappt** [comment]
Here is the updated UI
Screenshot from 2024-03-26 22-38-05
Screenshot from 2024-03-26 22-37-55

**Review by asikowitz — COMMENTED** [review]
Hmm, is there a way you can do this without hard coding the pixel amount? If we ever change the width of the first menu again, we'll have to update this as well. Or could we at least use a constant for the first menu's width, then use that in calculating `left` here

**Comment by sumitappt** [comment]
> Hmm, is there a way you can do this without hard coding the pixel amount? If we ever change the width of the first menu again, we'll have to update this as well. Or could we at least use a constant for the first menu's width, then use that in calculating `left` here

Done 
image

**Review by asikowitz — APPROVED** [review]
LGTM

**Pull request merged**
