### PR TITLE
fix(patch): consider escaped characters when applying JSON patches

### PR DESCRIPTION
**Pull request by ipolding-cais**
I have raised an issue for this: https://github.com/datahub-project/datahub/issues/10716

## Checklist

- [x] The PR conforms to DataHub's [Contributing Guideline](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [x] Links to related issues (if applicable)
- [x] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable). If a new feature has been added a Usage Guide has been added for the same.
- [ ] For any breaking change/potential downtime/deprecation/big changes an entry has been made in [Updating DataHub](https://github.com/datahub-project/datahub/blob/master/docs/how/updating-datahub.md)

## Summary by CodeRabbit

- **New Features**
  - Enhanced handling of special characters in paths for better compatibility.
  
- **Tests**
  - Added tests for JSON patches with special characters to ensure reliable functionality.

### CODE REVIEW

**Review by jjoyce0510 — COMMENTED** [review]
Hey there! We have an internal PR to fix this exact issue. Let me go ahead and raise that so you can avoid having to do this

**Review by jjoyce0510 — APPROVED** [review]
After changes, if CI is passing LGTM!

**Comment by jjoyce0510** [comment]
Do you mind running `./gradlew entity-registry:spotlessApply` to fix the linting CI issue with the test file?

Thanks!

**Comment by ipolding-cais** [comment]
There was a test failure for unrelated code `public void testSslVerificationException()` in `RestEmitterTest`

updating with master and trying again

**Pull request merged**
