### PR TITLE
fix(version): forUpdate needed for versioning

### PR DESCRIPTION
**Pull request by david-leifker**
* forUpdate is required for a read lock whenever calculating a version

## Checklist

- [ ] The PR conforms to DataHub's [Contributing Guideline](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [ ] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable). If a new feature has been added a Usage Guide has been added for the same.
- [ ] For any breaking change/potential downtime/deprecation/big changes an entry has been made in [Updating DataHub](https://github.com/datahub-project/datahub/blob/master/docs/how/updating-datahub.md)

### CODE REVIEW

**Review by pedro93 — APPROVED** [review]

**Comment by Masterchen09** [comment]
Hi @david-leifker,

I just noticed that when you are using a PostgreSQL database the changes in [EbeanAspectDao.java](https://github.com/datahub-project/datahub/pull/11328/files#diff-1edcb1179046da29e53dc904283429bfd75010abaf0a067453917d3936f36964) regarding the forUpdate are causing a NullPointerException when starting the GMS now:

```
2024-09-10 21:14:32,143 [pool-2-thread-1] ERROR c.l.metadata.boot.BootstrapManager:40 - Caught exception while executing bootstrap step IngestDataPlatformsStep. Exiting...
2024-09-10 23:14:32 java.lang.NullPointerException: Cannot invoke "io.ebean.Query$LockType.ordinal()" because "lockType" is null
2024-09-10 23:14:32     at io.ebean.config.dbplatform.postgres.PostgresPlatform.lock(PostgresPlatform.java:140)
2024-09-10 23:14:32     at io.ebean.config.dbplatform.postgres.PostgresPlatform.withForUpdate(PostgresPlatform.java:135)
2024-09-10 23:14:32     at io.ebean.config.dbplatform.DatabasePlatform.completeSql(DatabasePlatform.java:717)
2024-09-10 23:14:32     at io.ebeaninternal.server.query.CQueryBuilder$BuildReq.buildSql(CQueryBuilder.java:729)
2024-09-10 23:14:32     at io.ebeaninternal.server.query.CQueryBuilder$BuildReq.access$100(CQueryBuilder.java:530)
2024-09-10 23:14:32     at io.ebeaninternal.server.query.CQueryBuilder.buildSql(CQueryBuilder.java:519)
2024-09-10 23:14:32     at io.ebeaninternal.server.query.CQueryBuilder.buildFetchAttributeQuery(CQueryBuilder.java:198)
2024-09-10 23:14:32     at io.ebeaninternal.server.query.CQueryBuilder.buildFetchIdsQuery(CQueryBuilder.java:215)
2024-09-10 23:14:32     at io.ebeaninternal.server.query.CQueryEngine.findIds(CQueryEngine.java:145)
2024-09-10 23:14:32     at io.ebeaninternal.server.query.DefaultOrmQueryEngine.findIds(DefaultOrmQueryEngine.java:96)
2024-09-10 23:14:32     at io.ebeaninternal.server.core.OrmQueryRequest.findIds(OrmQueryRequest.java:355)
2024-09-10 23:14:32     at io.ebeaninternal.server.core.DefaultServer.findIdsWithCopy(DefaultServer.java:1276)
2024-09-10 23:14:32     at io.ebeaninternal.server.core.DefaultServer.findIds(DefaultServer.java:1259)
2024-09-10 23:14:32     at io.ebeaninternal.server.querydefn.DefaultOrmQuery.findIds(DefaultOrmQuery.java:1418)
2024-09-10 23:14:32     at com.linkedin.metadata.entity.ebean.EbeanAspectDao.getNextVersions(EbeanAspectDao.java:828)
2024-09-10 23:14:32     at com.linkedin.metadata.entity.EntityUtils.calculateNextVersions(EntityUtils.java:336)
2024-09-10 23:14:32     at com.linkedin.metadata.entity.EntityServiceImpl.lambda$ingestAspectsToLocalDB$40(EntityServiceImpl.java:853)
2024-09-10 23:14:32     at com.linkedin.metadata.entity.ebean.EbeanAspectDao.runInTransactionWithRetryUnlocked(EbeanAspectDao.java:742)
2024-09-10 23:14:32     at com.linkedin.metadata.entity.ebean.EbeanAspectDao.runInTransactionWithRetry(EbeanAspectDao.java:717)
2024-09-10 23:14:32     at com.linkedin.metadata.entity.EntityServiceImpl.ingestAspectsToLocalDB(EntityServiceImpl.java:837)
2024-09-10 23:14:32     at com.linkedin.metadata.entity.EntityServiceImpl.ingestAspects(EntityServiceImpl.java:773)
2024-09-10 23:14:32     at com.linkedin.metadata.boot.steps.IngestDataPlatformsStep.execute(IngestDataPlatformsStep.java:108)
2024-09-10 23:14:32     at com.linkedin.metadata.boot.BootstrapManager.start(BootstrapManager.java:38)
2024-09-10 23:14:32     at com.linkedin.metadata.boot.OnBootApplicationListener.lambda$isSchemaRegistryAPIServletReady$0(OnBootApplicationListener.java:109)
2024-09-10 23:14:32     at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
2024-09-10 23:14:32     at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
2024-09-10 23:14:32     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
2024-09-10 23:14:32     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
2024-09-10 23:14:32     at java.base/java.lang.Thread.run(Thread.java:840)
```

I have reproduced this on a local build on https://github.com/datahub-project/datahub/tree/837d00d391a9f3c6d79cbed9969fe4003e36f580.

I am not sure whether this is caused by a bug in the Ebean ORM library or if there must be changed something else regarding the forUpdate in EbeanAspectDao...what I was able to find out is that the PostgresPlatform seems to be using the lockType (which is null) in withForUpdate resp. lock, while the BaseMySqlPlatform (parent of MySqlPlatform) is ignoring the parameter (therefore it does not matter that the lockType is null):

https://github.com/ebean-orm/ebean/blob/12.16.3/ebean-api/src/main/java/io/ebean/config/dbplatform/postgres/PostgresPlatform.java#L128

https://github.com/ebean-orm/ebean/blob/12.16.3/ebean-api/src/main/java/io/ebean/config/dbplatform/mysql/BaseMySqlPlatform.java#L64

Maybe you could check this? 😊

**Comment by Masterchen09** [comment]
Hi @david-leifker,

after digging a bit deeper I found this comment in the copy method in DefaultOrmQuery of the Ebean ORM library: https://github.com/ebean-orm/ebean/blob/edbd13c0754ed23fc8e4958a1f43dbc76c09026a/ebean-core/src/main/java/io/ebeaninternal/server/querydefn/DefaultOrmQuery.java#L746

The copy method of DefaultOrmQuery is called when findIds resp. findIdsWithCopy is called in DefaultServer - see also [here](https://github.com/ebean-orm/ebean/blob/04ff5e7995d0ca1988ecae93b151409cb15f4361/ebean-core/src/main/java/io/ebeaninternal/server/core/DefaultServer.java#L1259C50-L1259C54):

```
at io.ebeaninternal.server.core.DefaultServer.findIdsWithCopy(DefaultServer.java:1276)
at io.ebeaninternal.server.core.DefaultServer.findIds(DefaultServer.java:1259)
```

Although I do not fully understand the backgrounds, the mentioned issue sounds like forUpdate is incorrectly used in context of getNextVersions resp. in relation to findIds? Is it possible that forUpdate is also incorrectly used in getLatestAspects and in relation to findList (although it seems in relation to findList no copy of the query is created...)?

Maybe this helps you a bit?

**Comment by david-leifker** [comment]
@Masterchen09 - I will find a resolution here and get a PR up to fix it. This has proven effective in solving a production issue with mysql for us. Hopefully we can find a solution that will for both.

**Comment by david-leifker** [comment]
The exception seems to be resolved by updating the ebean library see -> https://github.com/datahub-project/datahub/pull/11379

**Pull request merged**
