### PR TITLE
fix(ingest/mssql): remove lower() method from sql_common get_db_name

### LINKED ISSUE #9857: convert_urns_to_lowercase: inconsistency of usage in SQLAlchemySource.get_db & get_identifier methods
**Describe the bug**
Link to slack [thread](https://datahubspace.slack.com/archives/C029A3M079U/p1707739499808849).

**To Reproduce**
Using 
https://github.com/datahub-project/datahub/blob/709c596867a17f8324a366b5bbec6a9002a4af7c/metadata-ingestion/src/datahub/ingestion/source/sql/sql_common.py#L392-L400
can lead to unexpected behaviour of urn creating. Despite of convert_urns_to_lowercase = True or False - database name will be in lowercase anyway.

**Additional context**
Investigating of relations between configs & modules leaded to next additional questions:
1.
https://github.com/datahub-project/datahub/blob/709c596867a17f8324a366b5bbec6a9002a4af7c/metadata-ingestion/src/datahub/ingestion/source/sql/mssql/source.py#L64 

has attribute 

https://github.com/datahub-project/datahub/blob/709c596867a17f8324a366b5bbec6a9002a4af7c/metadata-ingestion/src/datahub/ingestion/source/sql/mssql/source.py#L98-L101

but at the same moment LowerCaseDatasetUrnConfigMixin also have this attribute 

https://github.com/datahub-project/datahub/blob/709c596867a17f8324a366b5bbec6a9002a4af7c/metadata-ingestion/src/datahub/configuration/source_common.py#L57-L61

So, is this mistake or those attributes should perform different actions? If yes, why they have same name? If no, can we get rid off it from child class?

2.
When I`m trying to find explicit using of this attributes in code, I see only next things:

a)
https://github.com/datahub-project/datahub/blob/045c76a0e4014ce159acdb0ddfb0f2e1220c7c40/metadata-ingestion/src/datahub/ingestion/source/sql/mssql/source.py#L663

b)
https://github.com/datahub-project/datahub/blob/045c76a0e4014ce159acdb0ddfb0f2e1220c7c40/metadata-ingestion/src/datahub/ingestion/source/snowflake/snowflake_utils.py#L177

c)
https://github.com/datahub-project/datahub/blob/045c76a0e4014ce159acdb0ddfb0f2e1220c7c40/metadata-ingestion/src/datahub/ingestion/api/source.py#L208-L229

I did not check it yet, but does it mean, that we can rid off all explicit using of convert_urns_to_lowercase attribute, because this parent class have method:

https://github.com/datahub-project/datahub/blob/045c76a0e4014ce159acdb0ddfb0f2e1220c7c40/metadata-ingestion/src/datahub/ingestion/api/source_helpers.py#L183-L197 

Or, if take a look at this from opposite point of view, I see only two explicit usage of convert_urns_to_lowercase attribute: in SQLServerSource and SnowflakeCommonMixin. Does it mean, that in all others sources this mechanizm (converting urns to lowercase) does not work?

@hsheth2 Can you, please, look at it one more time and after it I will create PR according to Slack thread. Thanks.

### PR DESCRIPTION
**Pull request by sleeperdeep**
Closes #9857

### CODE REVIEW

**Comment by hsheth2** [comment]
@sleeperdeep looks like this is causing some tests to fail

**Comment by sleeperdeep** [comment]
@hsheth2 @mayurinehate 
Hi guys! Any objections to merge these changes?

**Comment by mayurinehate** [comment]
> @hsheth2 @mayurinehate Hi guys! Any objections to merge these changes?

My primary concern is that this is breaking change for URNs and this may impact existing setups. Please allow me some more time to assess the impact. @hsheth2 feel free to add if you have any thoughts on this.

**Comment by sleeperdeep** [comment]
Hi @mayurinehate! What is your thoughts? Any additional things, that should be fixed inside this PR?

**Comment by sleeperdeep** [comment]
@hsheth2 @mayurinehate @mhw @rubiojr Are you here?

**Review by hsheth2 — APPROVED** [review]

**Comment by sleeperdeep** [comment]
@mayurinehate ?

**Comment by mayurinehate** [comment]
> @mayurinehate ?

We have identified that this would primarily affect container urns for a few (3-tier) sources + stored procedure/jobs urns for sql server. First one being relatively not so important for any other relationships than "container hierachy" and second one being relatively newer feature, this change seems fine and not so harmful. Re-running with stateful ingestion should automatically clear up the entities with old URNS and add entities with new URNs, therefore not duplicating the containers or jobs. Do you mind adding a note in updating-datahub about this change and how to mitigate this on similar lines as this -> https://github.com/datahub-project/datahub/pull/9601/files#diff-8a490856796965613edb9d4377cc46b5019bbd92d76d59096189e55bd22e709b

**Comment by mayurinehate** [comment]
@sleeperdeep the diff doesn't look correct. Can you please check and remove accidentally added files ?

**Comment by sleeperdeep** [comment]
@mayurinehate Yes, I`m in progress with it.

**Pull request closed without merging**
