### PR TITLE
fix(ingest): unfreeze bigquery/snowflake column dataclass

### PR DESCRIPTION
**Pull request by mayurinehate**
## Checklist

- [ ] The PR conforms to DataHub's [Contributing Guideline](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [ ] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable). If a new feature has been added a Usage Guide has been added for the same.
- [ ] For any breaking change/potential downtime/deprecation/big changes an entry has been made in [Updating DataHub](https://github.com/datahub-project/datahub/blob/master/docs/how/updating-datahub.md)

### CODE REVIEW

**Comment by hsheth2** [comment]
@mayurinehate what's the motivation for this change?

**Comment by mayurinehate** [comment]
> @mayurinehate what's the motivation for this change?

Freezing these classes restricts us from adding fields in Column class that will be initialized later. From what I have seen, there is no need to impose this restriction for any existing feature.
For example `tags` for a column could be added to `SnowflakeColumn` instead of `column_tags` in `SnowflakeTable` if the Column class was not frozen. This need not change now but unfreezing columns can make such things possible in future.

**Comment by hsheth2** [comment]
@mayurinehate do you have a sense of why they were marked as frozen to begin with? Normally we mark stuff as frozen if we need to use it as a key in a dict or in a set, but it does seem like the tests are passing so maybe it's not a problem.

**Comment by mayurinehate** [comment]
@hsheth2 I am not sure. I believe `BigQueryColumn` was marked frozen first in this ([commit](https://github.com/datahub-project/datahub/commit/3b9e9793a73c761cdc2fdd7b6c987c17c6b86ee6)) . `BaseColumn` and `SnowflakeColumn` were marked frozen as part of [this](https://github.com/datahub-project/datahub/commit/9a1f78fc60f692ebbd57c0a8cbabe4bfde44376b) refractor as mypy complains if child or parent class of frozen class is not frozen.

**Comment by hsheth2** [comment]
@mayurinehate ok sounds good - I think as long as tests are passing and @treff7es is ok with it, we should be ok to merge

**Pull request merged**
