### PR TITLE
perf(matadata-io): neo4j generateLineageStatement use shortestPath

### PR DESCRIPTION
**Pull request by shidianshifen**
nested/circle relation or lineage between tables as show below would lead to expensive match cypher results get from neo4j database
```mermaid
graph LR
B(table_B) --> |DownstreamOf| A(table_A)
D(table_D) -->|DownstreamOf| A(table_A)
C(table_C) -->|DownstreamOf| B(table_B)
D(table_D) -->|DownstreamOf| B(table_B)
C(table_C) -->|DownstreamOf| D(table_D)
E(table_E) -->|DownstreamOf| D(table_D)
F(table_F) -->|DownstreamOf| E(table_E)
D(table_D) -->|DownstreamOf| F(table_F)
```
find all table_A downstream tables using current cypher:  
```cypher
MATCH path=(a {urn: 'urn:li:dataset:(urn:li:dataPlatform:bigquery,table_A,PROD)'})<-[r:DownstreamOf*1..1000]-(b) 
WHERE b:dataJob OR b:dataProcess OR b:mlFeature OR b:dataset OR b:chart OR b:dashboard OR b:mlPrimaryKey 
RETURN a,nodes(path) as related_nodes, size(r), b
```
results:
| index | a                                                                  | related_nodes                                                                                                                                                                                                                                                                                                                                                                                                                                                                          | path_length | b                                                                  |
|-------|--------------------------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-------------|--------------------------------------------------------------------|
| 1     | {"urn":urn:li:dataset:(urn:li:dataPlatform:bigquery,table_A,PROD)} | [{"urn":urn:li:dataset:(urn:li:dataPlatform:bigquery,table_A,PROD)},{"urn":urn:li:dataset:(urn:li:dataPlatform:bigquery,table_B,PROD)}]                                                                                                                                                                                                                                                                                                                                                | 1           | {"urn":urn:li:dataset:(urn:li:dataPlatform:bigquery,table_B,PROD)} |
| 2     | {"urn":urn:li:dataset:(urn:li:dataPlatform:bigquery,table_A,PROD)} | [{"urn":urn:li:dataset:(urn:li:dataPlatform:bigquery,table_A,PROD)},{"urn":urn:li:dataset:(urn:li:dataPlatform:bigquery,table_B,PROD)},{"urn":urn:li:dataset:(urn:li:dataPlatform:bigquery,table_D,PROD)}]                                                                                                                                                                                                                                                                             | 2           | {"urn":urn:li:dataset:(urn:li:dataPlatform:bigquery,table_D,PROD)} |
| 3     | {"urn":urn:li:dataset:(urn:li:dataPlatform:bigquery,table_A,PROD)} | [{"urn":urn:li:dataset:(urn:li:dataPlatform:bigquery,table_A,PROD)},{"urn":urn:li:dataset:(urn:li:dataPlatform:bigquery,table_B,PROD)},{"urn":urn:li:dataset:(urn:li:dataPlatform:bigquery,table_D,PROD)},{"urn":urn:li:dataset:(urn:li:dataPlatform:bigquery,table_C,PROD)}]                                                                                                                                                                                                          | 3           | {"urn":urn:li:dataset:(urn:li:dataPlatform:bigquery,table_C,PROD)} |
| 4     | {"urn":urn:li:dataset:(urn:li:dataPlatform:bigquery,table_A,PROD)} | [{"urn":urn:li:dataset:(urn:li:dataPlatform:bigquery,table_A,PROD)},{"urn":urn:li:dataset:(urn:li:dataPlatform:bigquery,table_B,PROD)},{"urn":urn:li:dataset:(urn:li:dataPlatform:bigquery,table_D,PROD)},{"urn":urn:li:dataset:(urn:li:dataPlatform:bigquery,table_E,PROD)}]                                                                                                                                                                                                          | 3           | {"urn":urn:li:dataset:(urn:li:dataPlatform:bigquery,table_E,PROD)} |
| 5     | {"urn":urn:li:dataset:(urn:li:dataPlatform:bigquery,table_A,PROD)} | [{"urn":urn:li:dataset:(urn:li:dataPlatform:bigquery,table_A,PROD)},{"urn":urn:li:dataset:(urn:li:dataPlatform:bigquery,table_B,PROD)},{"urn":urn:li:dataset:(urn:li:dataPlatform:bigquery,table_D,PROD)},{"urn":urn:li:dataset:(urn:li:dataPlatform:bigquery,table_E,PROD)},{"urn":urn:li:dataset:(urn:li:dataPlatform:bigquery,table_F,PROD)}]                                                                                                                                       | 4           | {"urn":urn:li:dataset:(urn:li:dataPlatform:bigquery,table_F,PROD)} |
| 6     | {"urn":urn:li:dataset:(urn:li:dataPlatform:bigquery,table_A,PROD)} | [{"urn":urn:li:dataset:(urn:li:dataPlatform:bigquery,table_A,PROD)},{"urn":urn:li:dataset:(urn:li:dataPlatform:bigquery,table_B,PROD)},{"urn":urn:li:dataset:(urn:li:dataPlatform:bigquery,table_D,PROD)},{"urn":urn:li:dataset:(urn:li:dataPlatform:bigquery,table_E,PROD)},{"urn":urn:li:dataset:(urn:li:dataPlatform:bigquery,table_F,PROD)},{"urn":urn:li:dataset:(urn:li:dataPlatform:bigquery,table_D,PROD)}]                                                                    | 5           | {"urn":urn:li:dataset:(urn:li:dataPlatform:bigquery,table_D,PROD)} |
| 7     | {"urn":urn:li:dataset:(urn:li:dataPlatform:bigquery,table_A,PROD)} | [{"urn":urn:li:dataset:(urn:li:dataPlatform:bigquery,table_A,PROD)},{"urn":urn:li:dataset:(urn:li:dataPlatform:bigquery,table_B,PROD)},{"urn":urn:li:dataset:(urn:li:dataPlatform:bigquery,table_D,PROD)},{"urn":urn:li:dataset:(urn:li:dataPlatform:bigquery,table_E,PROD)},{"urn":urn:li:dataset:(urn:li:dataPlatform:bigquery,table_F,PROD)},{"urn":urn:li:dataset:(urn:li:dataPlatform:bigquery,table_D,PROD)},{"urn":urn:li:dataset:(urn:li:dataPlatform:bigquery,table_C,PROD)}] | 6           | {"urn":urn:li:dataset:(urn:li:dataPlatform:bigquery,table_C,PROD)} |
| 8     | {"urn":urn:li:dataset:(urn:li:dataPlatform:bigquery,table_A,PROD)} | [{"urn":urn:li:dataset:(urn:li:dataPlatform:bigquery,table_A,PROD)},{"urn":urn:li:dataset:(urn:li:dataPlatform:bigquery,table_B,PROD)},{"urn":urn:li:dataset:(urn:li:dataPlatform:bigquery,table_C,PROD)}]                                                                                                                                                                                                                                                                             | 2           | {"urn":urn:li:dataset:(urn:li:dataPlatform:bigquery,table_C,PROD)} |
| 9     | {"urn":urn:li:dataset:(urn:li:dataPlatform:bigquery,table_A,PROD)} | [{"urn":urn:li:dataset:(urn:li:dataPlatform:bigquery,table_A,PROD)},{"urn":urn:li:dataset:(urn:li:dataPlatform:bigquery,table_D,PROD)}]                                                                                                                                                                                                                                                                                                                                                | 1           | {"urn":urn:li:dataset:(urn:li:dataPlatform:bigquery,table_D,PROD)} |
| 10    | {"urn":urn:li:dataset:(urn:li:dataPlatform:bigquery,table_A,PROD)} | [{"urn":urn:li:dataset:(urn:li:dataPlatform:bigquery,table_A,PROD)},{"urn":urn:li:dataset:(urn:li:dataPlatform:bigquery,table_D,PROD)},{"urn":urn:li:dataset:(urn:li:dataPlatform:bigquery,table_C,PROD)}]                                                                                                                                                                                                                                                                             | 2           | {"urn":urn:li:dataset:(urn:li:dataPlatform:bigquery,table_C,PROD)} |
| 11    | {"urn":urn:li:dataset:(urn:li:dataPlatform:bigquery,table_A,PROD)} | [{"urn":urn:li:dataset:(urn:li:dataPlatform:bigquery,table_A,PROD)},{"urn":urn:li:dataset:(urn:li:dataPlatform:bigquery,table_D,PROD)},{"urn":urn:li:dataset:(urn:li:dataPlatform:bigquery,table_E,PROD)}]                                                                                                                                                                                                                                                                             | 2           | {"urn":urn:li:dataset:(urn:li:dataPlatform:bigquery,table_E,PROD)} |
| 12    | {"urn":urn:li:dataset:(urn:li:dataPlatform:bigquery,table_A,PROD)} | [{"urn":urn:li:dataset:(urn:li:dataPlatform:bigquery,table_A,PROD)},{"urn":urn:li:dataset:(urn:li:dataPlatform:bigquery,table_D,PROD)},{"urn":urn:li:dataset:(urn:li:dataPlatform:bigquery,table_E,PROD)},{"urn":urn:li:dataset:(urn:li:dataPlatform:bigquery,table_F,PROD)}]                                                                                                                                                                                                          | 3           | {"urn":urn:li:dataset:(urn:li:dataPlatform:bigquery,table_F,PROD)} |
| 13    | {"urn":urn:li:dataset:(urn:li:dataPlatform:bigquery,table_A,PROD)} | [{"urn":urn:li:dataset:(urn:li:dataPlatform:bigquery,table_A,PROD)},{"urn":urn:li:dataset:(urn:li:dataPlatform:bigquery,table_D,PROD)},{"urn":urn:li:dataset:(urn:li:dataPlatform:bigquery,table_E,PROD)},{"urn":urn:li:dataset:(urn:li:dataPlatform:bigquery,table_F,PROD)},{"urn":urn:li:dataset:(urn:li:dataPlatform:bigquery,table_D,PROD)}]                                                                                                                                       | 4           | {"urn":urn:li:dataset:(urn:li:dataPlatform:bigquery,table_D,PROD)} |
| 14    | {"urn":urn:li:dataset:(urn:li:dataPlatform:bigquery,table_A,PROD)} | [{"urn":urn:li:dataset:(urn:li:dataPlatform:bigquery,table_A,PROD)},{"urn":urn:li:dataset:(urn:li:dataPlatform:bigquery,table_D,PROD)},{"urn":urn:li:dataset:(urn:li:dataPlatform:bigquery,table_E,PROD)},{"urn":urn:li:dataset:(urn:li:dataPlatform:bigquery,table_F,PROD)},{"urn":urn:li:dataset:(urn:li:dataPlatform:bigquery,table_D,PROD)},{"urn":urn:li:dataset:(urn:li:dataPlatform:bigquery,table_C,PROD)}]                                                                    | 5           | {"urn":urn:li:dataset:(urn:li:dataPlatform:bigquery,table_C,PROD)} |

using neo4j shortestPath cypher become:
```cypher
MATCH path=shortestPath((a {urn: 'urn:li:dataset:(urn:li:dataPlatform:bigquery,table_A,PROD)'})<-[r:DownstreamOf*1..1000]-(b)) 
WHERE (b:dataJob OR b:dataProcess OR b:mlFeature OR b:dataset OR b:chart OR b:dashboard OR b:mlPrimaryKey) 
AND b.urn <> 'urn:li:dataset:(urn:li:dataPlatform:bigquery,table_A,PROD)'
RETURN a, nodes(path) as related_nodes, size(r) as path_length, b
```
results:
| index | a                                                                  | related_nodes                                                                                                                                                                                                                                                                 | path_length | b                                                                  |
|-------|--------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-------------|--------------------------------------------------------------------|
| 1     | {"urn":urn:li:dataset:(urn:li:dataPlatform:bigquery,table_A,PROD)} | [{"urn":urn:li:dataset:(urn:li:dataPlatform:bigquery,table_A,PROD)},{"urn":urn:li:dataset:(urn:li:dataPlatform:bigquery,table_B,PROD)}]                                                                                                                                       | 1           | {"urn":urn:li:dataset:(urn:li:dataPlatform:bigquery,table_B,PROD)} |
| 2     | {"urn":urn:li:dataset:(urn:li:dataPlatform:bigquery,table_A,PROD)} | [{"urn":urn:li:dataset:(urn:li:dataPlatform:bigquery,table_A,PROD)},{"urn":urn:li:dataset:(urn:li:dataPlatform:bigquery,table_D,PROD)}]                                                                                                                                       | 1           | {"urn":urn:li:dataset:(urn:li:dataPlatform:bigquery,table_D,PROD)} |
| 3     | {"urn":urn:li:dataset:(urn:li:dataPlatform:bigquery,table_A,PROD)} | [{"urn":urn:li:dataset:(urn:li:dataPlatform:bigquery,table_A,PROD)},{"urn":urn:li:dataset:(urn:li:dataPlatform:bigquery,table_D,PROD)},{"urn":urn:li:dataset:(urn:li:dataPlatform:bigquery,table_E,PROD)},{"urn":urn:li:dataset:(urn:li:dataPlatform:bigquery,table_F,PROD)}] | 3           | {"urn":urn:li:dataset:(urn:li:dataPlatform:bigquery,table_F,PROD)} |
| 4     | {"urn":urn:li:dataset:(urn:li:dataPlatform:bigquery,table_A,PROD)} | [{"urn":urn:li:dataset:(urn:li:dataPlatform:bigquery,table_A,PROD)},{"urn":urn:li:dataset:(urn:li:dataPlatform:bigquery,table_D,PROD)},{"urn":urn:li:dataset:(urn:li:dataPlatform:bigquery,table_C,PROD)}]                                                                    | 2           | {"urn":urn:li:dataset:(urn:li:dataPlatform:bigquery,table_C,PROD)} |
| 5     | {"urn":urn:li:dataset:(urn:li:dataPlatform:bigquery,table_A,PROD)} | [{"urn":urn:li:dataset:(urn:li:dataPlatform:bigquery,table_A,PROD)},{"urn":urn:li:dataset:(urn:li:dataPlatform:bigquery,table_D,PROD)},{"urn":urn:li:dataset:(urn:li:dataPlatform:bigquery,table_E,PROD)}]                                                                    | 2           | {"urn":urn:li:dataset:(urn:li:dataPlatform:bigquery,table_E,PROD)} |

The results pass to gms decreased significantly from 14 to 5. this could help to avoid gms oom and gc problem

## Checklist

- [x] The PR conforms to DataHub's [Contributing Guideline](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [ ] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable). If a new feature has been added a Usage Guide has been added for the same.
- [ ] For any breaking change/potential downtime/deprecation/big changes an entry has been made in [Updating DataHub](https://github.com/datahub-project/datahub/blob/master/docs/how/updating-datahub.md)

### CODE REVIEW

**Comment by shidianshifen** [comment]
@aditya-radhakrishnan hi, Could you help me review this patch?

**Comment by aditya-radhakrishnan** [comment]
Hey @shidianshifen sorry for the delay here! Have you been able to test these changes? Looks good to me though :)

**Comment by shidianshifen** [comment]
> Hey @shidianshifen sorry for the delay here! Have you been able to test these changes? Looks good to me though :)

yes, i tested with no problem. and i have are around 12000+ entities and 12 hops query results from neo4j decrease from 7 million to actual 1500+ using shortestPath

**Review by aditya-radhakrishnan — APPROVED** [review]
LGTM! Thank you for making this change :)

**Comment by aditya-radhakrishnan** [comment]
Will merge once CI is passing.

**Comment by shidianshifen** [comment]
@aditya-radhakrishnan Thanks very much for your review.

**Comment by shidianshifen** [comment]
@aditya-radhakrishnan this patch not merge in to master, should i do some else to make it happen? and neo4j graph backend not support for time filter in new release, i am prepare to commit a patch to make it work. what could be done next?

**Comment by aditya-radhakrishnan** [comment]
Hey @shidianshifen this is true, Neo4j time filtering is not supported with the new release. We can merge this one separately and then collaborate on updating for time filtering! Can you message me on Slack?

**Comment by aditya-radhakrishnan** [comment]
CI is running now (not sure why it didn't before). Will merge once green, apologies it didn't go through before!

**Pull request merged**
