### PR TITLE
feat(ingest/lookml): correctly handle include directives from imported projects

### PR DESCRIPTION
**Pull request by hsheth2**
**The issue**
When processing this situation: Base Project file -> includes External Project file A -> includes External Project file B, the second include directive was not being processed correctly. This was because we were looking for file B's include path in the base project rather than realizing that file A was in the external project and hence internal links should stay within the External Project.

**How does this PR solve it?**
We properly retain the context of a file so that we can process its includes correctly. We're doing that by deriving `base_folder` (now called `resolved_project_folder`) from the active `project_name` + any include directives.

**What else is happening?**
- Because we now derive the `base_folder` from the `base_projects_folder` and the active `project_name`, we can remove the `base_folder` arg from the include resolver.
- I couldn't find any docs for this, but it seems the include path is sometimes '/{project_name}/{path_within_project}' (normally cross-project refs start with `//`). I'm adding some edge case handling to process that correctly. To do that, we need the name of the base/root project `root_project_name` (if one exists), so we also do the plumbing to pipe that info into the include resolver.

## Checklist

- [ ] The PR conforms to DataHub's [Contributing Guideline](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [ ] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable). If a new feature has been added a Usage Guide has been added for the same.
- [ ] For any breaking change/potential downtime/deprecation/big changes an entry has been made in [Updating DataHub](https://github.com/datahub-project/datahub/blob/master/docs/how/updating-datahub.md)

### CODE REVIEW

**Comment by jjoyce0510** [comment]
Can you add a PR description giving a high level overview of the changes that were required here? I'm having a hard time zooming out

**Comment by hsheth2** [comment]
@jjoyce0510 updated the PR desc with some docs about this change

**Comment by hsheth2** [comment]
@jjoyce0510 updated the PR desc with some docs about this change

**Review by shirshanka — APPROVED** [review]
LGTM

**Pull request merged**
