### PR TITLE
feat(airflow): retry callback, support ExternalTaskSensor subclasses

### LINKED ISSUE #6305: Datahub Airflow plugin does not emit task status for UP_FOR_RETRY status
**Describe the bug**
The Datahub Airflow plugin does not emit to Datahub when the status is UP_FOR_RETRY. It only emits for SUCESS or FAILURE

**To Reproduce**
1. Execute a retryable AIrflow task that fails
2. Check the logs and you will see status as UP_FOR_RETRY, but no logs indicating that status was emitted to Datahub.

**Expected behavior**
All task statuses are emitted to Datahub.

### PR DESCRIPTION
**Pull request by richenc**
… add properties

Closes #6305.

## Checklist

- [X] The PR conforms to DataHub's [Contributing Guideline](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [X] Links to related issues (if applicable)
- [X] Tests for the changes have been added/updated (if applicable)
- [X] Docs related to the changes have been added/updated (if applicable). If a new feature has been added a Usage Guide has been added for the same.
- [X] For any breaking change/potential downtime/deprecation/big changes an entry has been made in [Updating DataHub](https://github.com/datahub-project/datahub/blob/master/docs/how/updating-datahub.md)

### CODE REVIEW

**Comment by hsheth2** [comment]
@richenc This was a long-standing gap in our Airflow plugin, so thanks for taking a stab at it!

We'll be reviewing it soon.

**Comment by richenc** [comment]
@hsheth2 I noticed the v2 plugin released recently. I was wondering how that affects my PR.

**Comment by hsheth2** [comment]
@richenc this PR still applies for the v1 plugin and we can merge review/merge it in around v1 if we want. However, the v2 plugin uses the Airflow listener API (instead of the somewhat hacky policy mechanism that v1 uses), so we should be able to detect UP_FOR_RETRY events more reliably with v2. 

The external sensor changes seem reasonable and are part of common code between v1 and v2, so that logic should be ok to merge regardless

**Comment by richenc** [comment]
> @richenc this PR still applies for the v1 plugin and we can merge review/merge it in around v1 if we want. However, the v2 plugin uses the Airflow listener API (instead of the somewhat hacky policy mechanism that v1 uses), so we should be able to detect UP_FOR_RETRY events more reliably with v2.
> 
> The external sensor changes seem reasonable and are part of common code between v1 and v2, so that logic should be ok to merge regardless

@hsheth2  good to hear that the listener API is being used! I think that means it might be possible to emit the data flow runs as dataprocessinstances! I'm going to look into the v2 plugin so I can migrate and contribute to it in the future. 

I just rebased my branch to fix the conflicts. Please let me know if there is anything else I need to do before this can be merged.

**Review by hsheth2 — APPROVED** [review]
The code looks good

Do you have a sense for how we'd implement something similar with the v2 plugin (using the listener API)?

**Comment by richenc** [comment]
> The code looks good
> 
> Do you have a sense for how we'd implement something similar with the v2 plugin (using the listener API)?

thanks @hsheth2! At the moment, I'm not sure but I was thinking about taking a crack at it once I had some time to test the v2 plugin in our local environment in preparation for migrating.

**Pull request merged**
