### PR TITLE
fix(ingest): use certs correctly in rest emitter

### PR DESCRIPTION
**Pull request by hsheth2**
Fixes https://github.com/datahub-project/datahub/issues/7923

## Checklist

- [ ] The PR conforms to DataHub's [Contributing Guideline](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [ ] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable). If a new feature has been added a Usage Guide has been added for the same.
- [ ] For any breaking change/potential downtime/deprecation/big changes an entry has been made in [Updating DataHub](https://github.com/datahub-project/datahub/blob/master/docs/how/updating-datahub.md)

### CODE REVIEW

**Review by treff7es — APPROVED** [review]

**Comment by kvandenhoute** [comment]
Hi @hsheth2, @treff7es ,

FYI: This breaks the ingestion with a custom CA.

https://github.com/datahub-project/datahub/blob/master/metadata-ingestion/src/datahub/ingestion/graph/client.py#L108 
 DataHubGraph inherits from DatahubRestEmitter. For the DataHubGraph self.session.verify is correct (https://requests.readthedocs.io/en/latest/user/advanced/#ssl-cert-verification), not self.session.cert

**Comment by hsheth2** [comment]
@kvandenhoute That's not great! Is this something you'd be able to open a PR for?

**Comment by kvandenhoute** [comment]
Hey @hsheth2,

I was going to,  but as I was looking into this it seems like the DatahubRestEmitter is used in more than just the DataHubGraph class and thus not that quick a fix .
My suggestion would either be to redesign a little bit so DatahubRestEmitter is not used for DatahubIngest classes, or to undo this PR and look for a different solution for the initial problem. As I don't really have familiarity with the project nor the time this is unfortunately something I won't do.

**Comment by jkadambi** [comment]
Hello @hsheth2, as pointed by @kvandenhoute, we are also facing a similar error with our ingestion due to the session cert change from verify introduced in 10.4. As pointed in the article above, in this case, based on the documentation provided, we are passing a ca cert path, which fails with the SSL validation error - Failed to connect to DataHub: HTTPSConnectionPool(host='xxxxx', port=xxx): Max retries exceeded with url: /config (Caused by SSLError(SSLError(9, '[SSL] PEM lib (_ssl.c:4065)')))

Could this change be reverted back to session verify until a workable solution is in place? I could create a PR if needed to undo this change. Thanks!

**Comment by hsheth2** [comment]
@kvandenhoute @jkadambi we've made a tweak in https://github.com/datahub-project/datahub/pull/8581 that should make this work a bit better.

**Pull request merged**
