### PR TITLE
Fix data search for fieldType = OBJECT for non-string fields

### PR DESCRIPTION
**Pull request by udbhav-hbk**
## Checklist

- [x] The PR conforms to DataHub's [Contributing Guideline](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [x] Links to related issues (if applicable)
- [x] Tests for the changes have been added/updated (if applicable)
- [x] Docs related to the changes have been added/updated (if applicable). If a new feature has been added a Usage Guide has been added for the same.
- [x] For any breaking change/potential downtime/deprecation/big changes an entry has been made in [Updating DataHub](https://github.com/datahub-project/datahub/blob/master/docs/how/updating-datahub.md)

### CODE REVIEW

**Comment by udbhav-hbk** [comment]
@david-leifker  Can you please review the PR? Thanks!

**Comment by david-leifker** [comment]
@udbhav-hbk - seeing some linting errors. Please run `./gradlew spotlessApply --rerun-tasks` to make sure it gets re-run on all modules. Then commit those formatting changes. Thank you!

**Comment by udbhav-hbk** [comment]
> @udbhav-hbk - seeing some linting errors. Please run `./gradlew spotlessApply --rerun-tasks` to make sure it gets re-run on all modules. Then commit those formatting changes. Thank you!

@david-leifker  Fixed linting issues, please have a look

**Comment by david-leifker** [comment]
@udbhav-hbk still getting test failures on linting
```
369 actionable tasks: 315 executed, 47 from cache, 7 up-to-date
           ··@Test
           ··public·void·testGetQueryBuilderForObjectFields()·{
           ····final·Criterion·singleValueCriterion·=
          -············new·Criterion()
          -····················.setField("testObjectField.numericField")
          -····················.setCondition(Condition.EQUAL)
          -····················.setValues(new·StringArray(ImmutableList.of("10")));
          +········new·Criterion()
          +············.setField("testObjectField.numericField")
          +············.setCondition(Condition.EQUAL)
          +············.setValues(new·StringArray(ImmutableList.of("10")));
           
           ····Map<String,·Set<SearchableAnnotation.FieldType>>·searchableFieldTypes·=·new·HashMap<>();
           ····searchableFieldTypes.put("testObjectField",·Set.of(SearchableAnnotation.FieldType.DOUBLE));
           
           ····QueryBuilder·result·=
          -············ESUtils.getQueryBuilderFromCriterion(
          -····················singleValueCriterion,
          -····················false,
          -····················searchableFieldTypes,
          -····················mock(OperationContext.class),
          -····················QueryFilterRewriteChain.EMPTY);
          +········ESUtils.getQueryBuilderFromCriterion(
          +············singleValueCriterion,
          +············false,
          +············searchableFieldTypes,
          +············mock(OperationContext.class),
          +············QueryFilterRewriteChain.EMPTY);
           ····String·expected·=
          -············"{\n"
          -····················+·"··\"terms\"·:·{\n"
          -····················+·"····\"testObjectField.numericField\"·:·[\n"
          -····················+·"······10.0\n"
          -····················+·"····],\n"
          -····················+·"····\"boost\"·:·1.0,\n"
          -····················+·"····\"_name\"·:·\"testObjectField.numericField\"\n"
          -····················+·"··}\n"
          -····················+·"}";
          +········"{\n"
          +············+·"··\"terms\"·:·{\n"
          +············+·"····\"testObjectField.numericField\"·:·[\n"
          +············+·"······10.0\n"
          +············+·"····],\n"
          +············+·"····\"boost\"·:·1.0,\n"
          +············+·"····\"_name\"·:·\"testObjectField.numericField\"\n"
          +············+·"··}\n"
          +············+·"}";
           ····Assert.assertEquals(result.toString(),·expected);
      ... (48 more lines that didn't fit)
  Run './gradlew :metadata-io:spotlessApply' to fix these violations.
```

**Review by david-leifker — APPROVED** [review]

**Comment by Nbagga14** [comment]
@david-leifker Since this PR has been merged, could you please let us know in which upcoming release we can expect it to be included? Additionally, could you share the roadmap or any planned updates for future DataHub releases?

**Comment by david-leifker** [comment]
@Nbagga14 - `v0.14.2` is the next release, I do not have a timeline for it at the moment.

**Pull request merged**
