### PR TITLE
fix(docs): fixes link to developers guides

### PR DESCRIPTION
**Pull request by sgomezvillamor**
This is the redirection I expect when I click on "developer guides".
Being redirected to "DataHub CLI" always confused me
So proposing this change

## Checklist

- [ ] The PR conforms to DataHub's [Contributing Guideline](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [ ] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable). If a new feature has been added a Usage Guide has been added for the same.
- [ ] For any breaking change/potential downtime/deprecation/big changes an entry has been made in [Updating DataHub](https://github.com/datahub-project/datahub/blob/master/docs/how/updating-datahub.md)

### CODE REVIEW

**Comment by sgomezvillamor** [comment]
ICYMI @maggiehays This may not be an error but a feature, however current redirection always confused me, so trying to fix here 😅

**Review by jjoyce0510 — COMMENTED** [review]
I would actually prefer this to link to "https://datahubproject.io/docs/api/datahub-apis" 

which is the base for all the API + CLI docs for datahub. 

My understanding is that our developer facing docs are primarily about _using datahub_ as opposed to really developing on datahub core :)  -- so should be more API focused.

I'll let @yoonhyejin  add any thoughts!

**Comment by yoonhyejin** [comment]
Thanks @sgomezvillamor for raising this! I def agree that the redirection to /cli is a bit confusing. Also agree with @jjoyce0510 - I think the use case here is more on the API/SDKs side.

**Comment by sgomezvillamor** [comment]
Thanks for the review @jjoyce0510 and @yoonhyejin . I did apply you suggestion in 165c592 and once deployed https://docs-website-lmqydzp5o-acryldata.vercel.app/docs/ I realized that there is already a "box" for API, so such a redirect in "Developer Guides" is redundant.

Captura de Pantalla 2023-09-21 a las 7 02 52

Maybe the "Developer Guides" may be renamed to "Contributor Guides"

```
  {
    title: "Contributor Guides",
    icon: <CodeTwoTone />,
    description: "Developing on DataHub",
    to: "/docs/developers",
  },
```

or just removing the box at all

**Review by hsheth2 — APPROVED** [review]

**Pull request merged**
