### PR TITLE
feat(docker):Add the jattach tool to the docker container(#7538)

### PR DESCRIPTION
**Pull request by yangjiandan**
Test:
1. docker run -it linkedin/datahub-gms:head /bin/sh
2. run jattach

The following is a screenshot of the execution in my local environment
image

## Checklist

- [x] The PR conforms to DataHub's [Contributing Guideline](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [x] Links to related issues (if applicable) - N/A
- [x] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable). If a new feature has been added a Usage Guide has been added for the same.
- [x] For any breaking change/potential downtime/deprecation/big changes an entry has been made in [Updating DataHub](https://github.com/datahub-project/datahub/blob/master/docs/how/updating-datahub.md) - N/A

### CODE REVIEW

**Comment by yangjiandan** [comment]
@meyerkev Thanks very much for your apply in https://github.com/datahub-project/datahub/pull/7539. I update patch using latest code, and add a attach-guide doc. 
Could you help review my patch again?

**Comment by yangjiandan** [comment]
all required checks have passed! some checked failed due network timeout and is not related to this modification.
@meyerkev

**Comment by yangjiandan** [comment]
@david-leifker Could you help me review this patch?

**Comment by david-leifker** [comment]
Taking a look here, need to get the docs process to be happy. Lets see if the update from master helps.

**Comment by yangjiandan** [comment]
@david-leifker thanks for your reply, I have fix doc issue. Please help me review this PR again.

**Review by david-leifker — APPROVED** [review]

**Pull request merged**
