### PR TITLE
fix(datahub-frontend): Add playCaffeine as replacement for removed playEhcache dependency

### PR DESCRIPTION
**Pull request by MideO**
## Checklist

- [X] The PR conforms to DataHub's [Contributing Guideline](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [X] Links to related issues (if applicable)
- [X] Tests for the changes have been added/updated (if applicable)
- [X] Docs related to the changes have been added/updated (if applicable). If a new feature has been added a Usage Guide has been added for the same.
- [X] For any breaking change/potential downtime/deprecation/big changes an entry has been made in [Updating DataHub](https://github.com/datahub-project/datahub/blob/master/docs/how/updating-datahub.md)

This is to resolve the issue described in https://github.com/datahub-project/datahub/issues/7733

### CODE REVIEW

**Comment by RyanHolstien** [comment]
The EhCache implementation is deprecated and considered legacy, can this be done using the play Caffeine impl?: https://mvnrepository.com/artifact/com.typesafe.play/play-caffeine-cache 

See:
`Play provides a CacheApi implementation based on [Caffeine](https://github.com/ben-manes/caffeine/) and a legacy implementation based on [Ehcache 2.x](http://www.ehcache.org/). For in-process caching Caffeine is typically the best choice. If you need distributed caching, there are third-party plugins for [memcached](https://github.com/mumoshu/play2-memcached) and [redis](https://github.com/KarelCemus/play-redis).`

https://www.playframework.com/documentation/2.8.x/ScalaCache

**Comment by MideO** [comment]
@RyanHolstien Thanks for the feedback, I've replaced play Ehcache with Caffeine.

**Comment by RyanHolstien** [comment]
This looks good to me, just waiting on CI to be green. We're actively working on fixing some flakiness so hoping your PR can get in after that.

**Comment by MideO** [comment]
bump @iprentic @RyanHolstien please can we get this merged in?

**Review by RyanHolstien — APPROVED** [review]

**Pull request merged**
