### PR TITLE
fix(ingest): databricks - support env

### LINKED ISSUE #6326: Env ignored when ingesting metadata from a unity catalog
**Describe the bug**
When ingesting the metadata from the new unity-catalog source, env is always set to PROD as it is not passed to the underlying urn generation methods. Otherwise, thanks for the great work on databricks ingestion

**To Reproduce**
1. ingest any databricks metadata via the cli

**Expected behavior**
Correct env value

### PR DESCRIPTION
**Pull request by ms32035**
Resolves #6326 

## Checklist

- [X] The PR conforms to DataHub's [Contributing Guideline](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [X] Links to related issues (if applicable)
- [X] Tests for the changes have been added/updated (if applicable)
- [X] Docs related to the changes have been added/updated (if applicable). If a new feature has been added a Usage Guide has been added for the same.
- [X] For any breaking change/potential downtime/deprecation/big changes an entry has been made in [Updating DataHub](https://github.com/datahub-project/datahub/blob/master/docs/how/updating-datahub.md)

### CODE REVIEW

**Comment by jjoyce0510** [comment]
Hi there! We are trying to move aware from "env" as a concept in DataHub (deprecating it).

is there a strong reason you want to use the env, as opposed Data Platform Instance (recommended) going forward?

**Comment by ms32035** [comment]
Not really, just for consistency with the current implementation

**Comment by jjoyce0510** [comment]
Okay - if there is not a strong use case driving this I'd suggest that we hold on this particular PR... We can always reopen it if the need arises later on. 

In the meantime, we are working to make this deprecation more clear to our users!

**Review by hsheth2 — APPROVED** [review]

**Review by hsheth2 — CHANGES_REQUESTED** [review]
Given @jjoyce0510's comments, imo it makes more sense to prefer `platform_instance_name` and hide the `env` config.

Does that work for you @ms32035?

**Comment by ms32035** [comment]
Yes, that's ok

**Pull request closed without merging**
