### PR TITLE
fix(ingest/airflow): reorder imports to avoid cyclical dependencies

### PR DESCRIPTION
**Pull request by stijndehaes**
Only import things needed for type checking when
type checking
Delay the import of some Airflow classes because
otherwise they result in an import cycle

## Checklist

- [x] The PR conforms to DataHub's [Contributing Guideline](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [x] Links to related issues (if applicable)
- [x] Tests for the changes have been added/updated (if applicable)
- [x] Docs related to the changes have been added/updated (if applicable). If a new feature has been added a Usage Guide has been added for the same.
- [x] For any breaking change/potential downtime/deprecation/big changes an entry has been made in [Updating DataHub](https://github.com/datahub-project/datahub/blob/master/docs/how/updating-datahub.md)

### CODE REVIEW

**Comment by hsheth2** [comment]
@stijndehaes what's the exact import that fails?

The `datahub_provider._airflow_compat` import has a side-effect of patching a bug in the `markupsafe` library dependency, so generally we want to import it as early as possible. It might be necessary to split the file into two.

**Comment by jjoyce0510** [comment]
Hi @stijndehaes ! Thanks for the contribution. Heads up -  If we do not hear back from you within another week we will move to close the PR due to inactivity.

Cheers
John

**Comment by stijndehaes** [comment]
Hi thank you for the reminder.
I will try to recreate the issue again this week and send you a version of the log :)

**Comment by stijndehaes** [comment]
I have added the log at the bottom of this post. 
Currently we are running airflow on kubernetes. We are using airflow 2.4.3 (this was not an issue with 2.3.x I believe).
There is a circular import now between airflow base operator and the lineage backend.

I hope this helps put the PR into context.


```

[2022-12-27 14:32:42,839] {settings.py:266} DEBUG - Setting up DB connection pool (PID 7)
[2022-12-27 14:32:42,840] {settings.py:371} DEBUG - settings.prepare_engine_args(): Using pool settings. pool_size=5, max_overflow=10, pool_recycle=1800, pid=7
[2022-12-27 14:32:42,904] {cli_action_loggers.py:39} DEBUG - Adding <function default_action_log at 0x7f0ce34c2670> to pre execution callback
[2022-12-27 14:32:43,207] {configuration.py:693} ERROR - cannot import name 'BaseOperator' from partially initialized module 'airflow.models.baseoperator' (most likely due to a circular import) (/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/configuration.py", line 691, in getimport
    return import_string(full_qualified_path)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/module_loading.py", line 33, in import_string
    module = import_module(module_path)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.9/site-packages/datahub_provider/lineage/datahub.py", line 7, in <module>
    from datahub_provider._lineage_core import (
  File "/home/airflow/.local/lib/python3.9/site-packages/datahub_provider/_lineage_core.py", line 1, in <module>
    from datahub_provider._airflow_compat import Operator
  File "/home/airflow/.local/lib/python3.9/site-packages/datahub_provider/_airflow_compat.py", line 3, in <module>
    from airflow.models.baseoperator import BaseOperator
ImportError: cannot import name 'BaseOperator' from partially initialized module 'airflow.models.baseoperator' (most likely due to a circular import) (/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/bin/airflow", line 8, in <module>
    sys.exit(main())
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/__main__.py", line 39, in main
    args.func(args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/cli_parser.py", line 51, in command
    func = import_string(import_path)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/module_loading.py", line 33, in import_string
    module = import_module(module_path)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 41, in <module>
    from airflow.models.baseoperator import BaseOperator
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 440, in <module>
    class BaseOperator(AbstractOperator, metaclass=BaseOperatorMeta):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 1130, in BaseOperator
    def post_execute(self, context: Any, result: Any = None):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/lineage/__init__.py", line 101, in apply_lineage
    _backend = get_backend()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/lineage/__init__.py", line 45, in get_backend
    clazz = conf.getimport("lineage", "backend", fallback=None)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/configuration.py", line 694, in getimport
    raise AirflowConfigException(
airflow.exceptions.AirflowConfigException: The object could not be loaded. Please check "backend" key in "lineage" section. Current value: "datahub_provider.lineage.datahub.DatahubLineageBackend".
[2022-12-27 14:32:43,209] {settings.py:407} DEBUG - Disposing DB connection pool (PID 7)
Stream closed EOF for sdh/samplepysparkgreeterv2-cee951ce4c244e81bc217d836b8fbc8c (base)

```

**Comment by hsheth2** [comment]
@stijndehaes I made some fixes for circular imports in this PR https://github.com/datahub-project/datahub/pull/6854. Could you try it again with version `0.9.5.1rc0`?

**Comment by stijndehaes** [comment]
@hsheth2 The error changes a bit because of the changed imports.
However it is still failing.

Any suggestions from you guys on how to proceed are welcome

```

[2022-12-28 10:33:51,372] {settings.py:266} DEBUG - Setting up DB connection pool (PID 7)
[2022-12-28 10:33:51,373] {settings.py:371} DEBUG - settings.prepare_engine_args(): Using pool settings. pool_size=5, max_overflow=10, pool_recycle=1800, pid=7
[2022-12-28 10:33:51,442] {cli_action_loggers.py:39} DEBUG - Adding <function default_action_log at 0x7f342f043670> to pre execution callback
[2022-12-28 10:33:52,122] {configuration.py:693} ERROR - cannot import name 'BaseOperator' from partially initialized module 'airflow.models.baseoperator' (most likely due to a circular import) (/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/configuration.py", line 691, in getimport
    return import_string(full_qualified_path)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/module_loading.py", line 33, in import_string
    module = import_module(module_path)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.9/site-packages/datahub_provider/lineage/datahub.py", line 7, in <module>
    from datahub_provider._lineage_core import (
  File "/home/airflow/.local/lib/python3.9/site-packages/datahub_provider/_lineage_core.py", line 8, in <module>
    from datahub_provider._airflow_shims import Operator
  File "/home/airflow/.local/lib/python3.9/site-packages/datahub_provider/_airflow_shims.py", line 3, in <module>
    from airflow.models.baseoperator import BaseOperator
ImportError: cannot import name 'BaseOperator' from partially initialized module 'airflow.models.baseoperator' (most likely due to a circular import) (/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/bin/airflow", line 8, in <module>
    sys.exit(main())
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/__main__.py", line 39, in main
    args.func(args)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/cli_parser.py", line 51, in command
    func = import_string(import_path)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/utils/module_loading.py", line 33, in import_string
    module = import_module(module_path)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/cli/commands/task_command.py", line 41, in <module>
    from airflow.models.baseoperator import BaseOperator
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 440, in <module>
    class BaseOperator(AbstractOperator, metaclass=BaseOperatorMeta):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 1130, in BaseOperator
    def post_execute(self, context: Any, result: Any = None):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/lineage/__init__.py", line 101, in apply_lineage
    _backend = get_backend()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/lineage/__init__.py", line 45, in get_backend
    clazz = conf.getimport("lineage", "backend", fallback=None)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/configuration.py", line 694, in getimport
    raise AirflowConfigException(
airflow.exceptions.AirflowConfigException: The object could not be loaded. Please check "backend" key in "lineage" section. Current value: "datahub_provider.lineage.datahub.DatahubLineageBackend".
[2022-12-28 10:33:52,124] {settings.py:407} DEBUG - Disposing DB connection pool (PID 7)
Stream closed EOF for sdh/samplepysparkgreeterv2-0fa8c6d9296049fba1b631cf75511d21 (base)
```

**Review by hsheth2 — APPROVED** [review]
Made a minor tweak to fix linting, but overall LGTM

**Pull request merged**
