### PR TITLE
feat(ingest): add ingest `--no-progress` option

### PR DESCRIPTION
**Pull request by BlueHorn07**
## Checklist

Hello, guys. I want to silent intermediate ingestion report.

When, I ingest data from Databricks or Redshift platform, it takes more than 30 minutes, and it generates large log files (ex. 11 Mb). I want to avoid this situation, as it slows down our logging platform.

I added `--quiet`, `-q` option on ingest-cli, before the `--dry-run`, but please let me know that it's order should be changed.

- [ ] The PR conforms to DataHub's [Contributing Guideline](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [ ] Tests for the changes have been added/updated (if applicable)
- [x] Docs related to the changes have been added/updated (if applicable). If a new feature has been added a Usage Guide has been added for the same.
- [ ] For any breaking change/potential downtime/deprecation/big changes an entry has been made in [Updating DataHub](https://github.com/datahub-project/datahub/blob/master/docs/how/updating-datahub.md)

### CODE REVIEW

**Review by hsheth2 — COMMENTED** [review]
I agree with the overall premise here - those messages can be annoyingly chatty at times

My main worry is the flag's naming. In most CLIs, `--quiet` suppresses _all_ log messages and is effectively the inverse of `--verbose`.

Can we rename quiet to `--no-progress` or `--no-print-progress` to more accurately reflect what it does?

**Comment by BlueHorn07** [comment]
Hello, @hsheth2, thanks for your comment :) I agree that your worry about expression `--quiet`. I think it's nice to replace the expression to `--no-progress`. I will change it, thanks!!

**Review by hsheth2 — APPROVED** [review]
LGTM

**Comment by BlueHorn07** [comment]
Thank you for taking care of this PR, @hsheth2. Please, schedule the PR can be merged 🙏

**Pull request merged**
