### PR TITLE
Show data platform instances in policy modal if they are set on the policy

### PR DESCRIPTION
**Pull request by githendrik**
See Slack discussion: https://datahubspace.slack.com/archives/CV2UXSE9L/p1706192011521399

As it is already possible through the api / sdk, to apply policies based on dataPlatformInstance, I wanted to have this surfaced at least when showing the policy modal. This PR doesn't go as far as enabling editing platformInstances through the UI, but this might be a step in the right direction at least :) Let me know what you think!

image

## Checklist

- [x] The PR conforms to DataHub's [Contributing Guideline](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [x] Links to related issues (if applicable)
- [ x Tests for the changes have been added/updated (if applicable)
- [x] Docs related to the changes have been added/updated (if applicable). If a new feature has been added a Usage Guide has been added for the same.
- [x] For any breaking change/potential downtime/deprecation/big changes an entry has been made in [Updating DataHub](https://github.com/datahub-project/datahub/blob/master/docs/how/updating-datahub.md)

## Summary by CodeRabbit

- **New Features**
  - Enhanced the policy details modal to display and handle `Data Platform Instances` with their display names.

### CODE REVIEW

**Review by chriscollins3456 — APPROVED** [review]
nice! thanks for this :)

**Comment by githendrik** [comment]
Any chance you could help me debug a failing e2e test? I don't *think* it's related to my change - but I also couldn't find a "re-run" button

Test in question:
```
  9 passing (3m)
  1 failing

  1) Verify nested domains test functionalities
       Verify Move domain parent level to root level:
     AssertionError: 2024-06-05T11:42:29.252Z
Timed out retrying after 10000ms: Expected to find element: `prev`, but never found it. Queried from:

              > cy.get([data-testid="domain-list-item"]).contains(Marketing)
  AssertionError: Timed out retrying after 10000ms: Expected to find element: `prev`, but never found it. Queried from:
  
                > cy.get([data-testid="domain-list-item"]).contains(Marketing)
      at moveDomaintoParent (webpack:///./cypress/e2e/domains/nested_domains.js:42:5)
      at Context.eval (webpack:///./cypress/e2e/domains/nested_domains.js:168:4)
```

**Comment by chriscollins3456** [comment]
> Any chance you could help me debug a failing e2e test? I don't _think_ it's related to my change - but I also couldn't find a "re-run" button

yup! i just re-ran the test and i believe it's just a flaky cypress test i've seen fail before. i'm almost certain this isn't caused by you so we can merge after it re-runs

**Comment by githendrik** [comment]
I've updated the branch to the latest version a couple of times now - which triggered a re-run of the tests.

Somehow it's always the same test failing:

```
  1) Verify nested domains test functionalities
       Verify Move domain parent level to root level:
     AssertionError: 2024-06-12T05:21:28.329Z
Timed out retrying after 10000ms: Expected to find element: `prev`, but never found it. Queried from:

              > cy.get([data-testid="domain-list-item"]).contains(Marketing)
  AssertionError: Timed out retrying after 10000ms: Expected to find element: `prev`, but never found it. Queried from:
  
                > cy.get([data-testid="domain-list-item"]).contains(Marketing)
      at moveDomaintoParent (webpack:///./cypress/e2e/domains/nested_domains.js:42:5)
      at Context.eval (webpack:///./cypress/e2e/domains/nested_domains.js:168:4)
```

However I cannot find any relation of this to my changes. Maybe I'm looking in the wrong place, but I don't understand how the Policies Modal could impact Nested Domains. But then again, master seems to be green, so now I'm a bit confused :)

Could you possibly assist here @chriscollins3456 ?

**Review by jjoyce0510 — APPROVED** [review]

**Comment by jjoyce0510** [comment]
CI appears to be failing! 

Please get ci in good shape by running the following inside the `datahub-web-react` module:

`yarn run prettier --write src`

**Comment by jjoyce0510** [comment]
It's mainly the yarnLint failing. You can look past the nestedDomains issue for now - we've been having problems with that test elsewhere

**Comment by githendrik** [comment]
> It's mainly the yarnLint failing. You can look past the nestedDomains issue for now - we've been having problems with that test elsewhere

Okay, thanks! Fixed the linting issues just now.

**Pull request merged**
