### PR TITLE
docs(ingest/kafka): add field descriptions of kafka-related configs to pydantic

### PR DESCRIPTION
**Pull request by mmmeeedddsss**
Added descriptions of kafka-related configs to pydantic so that these can appear on the datahub's documentation page. (e.g see https://datahubproject.io/docs/generated/ingestion/sources/kafka#config-details)

### CODE REVIEW

**Review by hsheth2 — APPROVED** [review]
Thanks for fixing this!

**Comment by hsheth2** [comment]
@mmmeeedddsss looks like the linter is failing

Could you run `./gradlew :metadata-ingestion:lintFix`?

**Comment by mmmeeedddsss** [comment]
@hsheth2 I guess I managed to pass lint checks but seems like another test is failing. It seemed unrelated to me. Is there an issue on master?

**Comment by hsheth2** [comment]
@mmmeeedddsss agree that it seems unrelated, so I've merged it.

**Pull request merged**
