### PR TITLE
feat(ingest/databricks): include metadata for browse only tables

### PR DESCRIPTION
**Pull request by mayurinehate**
also contains bug fix for hive metastore views

## Checklist

- [ ] The PR conforms to DataHub's [Contributing Guideline](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [ ] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable). If a new feature has been added a Usage Guide has been added for the same.
- [ ] For any breaking change/potential downtime/deprecation/big changes an entry has been made in [Updating DataHub](https://github.com/datahub-project/datahub/blob/master/docs/how/updating-datahub.md)

### CODE REVIEW

**Review by jjoyce0510 — APPROVED** [review]
Assuming connector tests, ci passing we should be good to go

**Review by jjoyce0510 — APPROVED** [review]
Assuming connector tests, ci passing we should be good to go.

Also, should we be updating a unit test?

Or perhaps, add a screenrecording or QA section to the PR description

**Comment by hsheth2** [comment]
@mayurinehate is this mergable?

**Comment by mayurinehate** [comment]
@hsheth2 I fixed a test, so this is mergeable now.

**Pull request merged**
