### PR TITLE
fix(ingest): fix handling of spaces in complex hive types (#6157)

### LINKED ISSUE #6157: Glue ingestion fails if AWS returns a space before <
**Describe the bug**
Metadata Ingestion fails because AWS Glue column type may contain space before `<` in complex types (array / struct / etc)

**To Reproduce**
1. Add AWS Glue ingestion
2. Store a table in AWS Glue with column type with space before complex type (e.g. `array < struct <  user_id: string>>`)
3. Execute an ingestion

**Expected behavior**
Ingestion executes without errors

**Actual behavior**
Type is not recognized because of the space
```
Unable to parse column users and type array < struct <  user_id: string>> the error was: The struct field string format is: 'field_name:field_type', but got: array < struct <  user_id: string>>
```

### PR DESCRIPTION
**Pull request by kirillmakhonin**
This closes #6157 

## Checklist
- [x] The PR conforms to DataHub's [Contributing Guideline](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [x] Links to related issues (if applicable)
- [x] Tests for the changes have been added/updated (if applicable)
- [x] (Not applicable) Docs related to the changes have been added/updated (if applicable). If a new feature has been added a Usage Guide has been added for the same.
- [x] (Not applicable) For any breaking change/potential downtime/deprecation/big changes an entry has been made in [Updating DataHub](https://github.com/datahub-project/datahub/blob/master/docs/how/updating-datahub.md)

### CODE REVIEW

**Comment by jjoyce0510** [comment]
Looks like lint is failing due to Optionals! Once we address we are good to merge this in :)

**Review by hsheth2 — CHANGES_REQUESTED** [review]
@kirillmakhonin would you mind fixing the lint issue?

```
+ mypy --show-traceback --show-error-codes src/ tests/ examples/
src/datahub/utilities/hive_schema_to_avro.py:74: error: Argument 1 to "_parse_datatype_string" of "HiveColumnToAvroConverter" has incompatible type "Optional[str]"; expected "str"  [arg-type]
src/datahub/utilities/hive_schema_to_avro.py:80: error: Argument 1 to "_ignore_brackets_split" of "HiveColumnToAvroConverter" has incompatible type "Optional[str]"; expected "str"  [arg-type]
src/datahub/utilities/hive_schema_to_avro.py:102: error: Argument 1 to "_ignore_brackets_split" of "HiveColumnToAvroConverter" has incompatible type "Optional[str]"; expected "str"  [arg-type]
src/datahub/utilities/hive_schema_to_avro.py:120: error: Argument 1 to "_parse_struct_fields_string" of "HiveColumnToAvroConverter" has incompatible type "Optional[str]"; expected "str"  [arg-type]
Found 4 errors in 1 file (checked 606 source files)
```

**Comment by jjoyce0510** [comment]
Hi @kirillmakhonin - Did you plan to update this PR? 

Otherwise, the Acryl team will take ownership of this change.

**Comment by jjoyce0510** [comment]
Closing this for now. Acryl team will take it from here.

Cheers
John

**Pull request closed without merging**
