### PR TITLE
feat(ingest/tableau): support platform instance mapping based off database server hostname

### PR DESCRIPTION
**Pull request by richenc**
## Checklist

- [x] The PR conforms to DataHub's [Contributing Guideline](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [x] Links to related issues (if applicable)
- [x] Tests for the changes have been added/updated (if applicable)
- [x] Docs related to the changes have been added/updated (if applicable). If a new feature has been added a Usage Guide has been added for the same.
- [x] For any breaking change/potential downtime/deprecation/big changes an entry has been made in [Updating DataHub](https://github.com/datahub-project/datahub/blob/master/docs/how/updating-datahub.md)

### CODE REVIEW

**Comment by gabe-lyons** [comment]
@mayurinehate can you take a look here?

**Review by mayurinehate — APPROVED** [review]
LGTM

**Comment by richenc** [comment]
I'm not sure why the documentation/gh-pages step is failing. Seeing the following in the details:
```
/home/runner/work/datahub/datahub/docs-website/generateDocsDir.ts:28
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
  throttle: {
                                                         ^
Error: File not accounted for in sidebar: docs/managed-datahub/observe/schema-assertions.md - try adding it to docs-website/sidebars.js
    at /home/runner/work/datahub/datahub/docs-website/generateDocsDir.ts:641:13
    at Generator.next (<anonymous>)
    at fulfilled (/home/runner/work/datahub/datahub/docs-website/generateDocsDir.ts:28:58)
error Command failed with exit code 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

> Task :docs-website:yarnGenerate FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':docs-website:yarnGenerate'.
> Process 'command '/home/runner/work/datahub/datahub/docs-website/.gradle/yarn/yarn-v1.22.1/bin/yarn'' finished with non-zero exit value 1
```

**Comment by gabe-lyons** [comment]
looks like that file was introduced recently, https://github.com/datahub-project/datahub/pull/10473/files. I updated your branch to see if that addresses it.

**Review by gabe-lyons — APPROVED** [review]

**Pull request merged**
