### PR TITLE
fix(airflow): fix AthenaOperator extraction

### LINKED ISSUE #11160: Datahub Airflow plugin throws error: AttributeError: 'AthenaOperator' object has no attribute 'sql'
**Describe the bug**

The Datahub Airflow plugin is throwing the following error when using the AthenaOperator. 
```
[2024-08-13, 12:30:02 UTC] {{manager.py:69}} ERROR - Failed to extract metadata 'AthenaOperator' object has no attribute 'sql' task_type=AthenaOperator ***_dag_id=my_dag task_id=my_task ***_run_id=scheduled__2024-08-12T00:00:00+00:00 
Traceback (most recent call last):
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/openlineage/airflow/extractors/manager.py", line 45, in extract_metadata
    task_metadata = extractor.extract_on_complete(task_instance)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/openlineage/airflow/extractors/base.py", line 68, in extract_on_complete
    return self.extract()
           ^^^^^^^^^^^^^^
  File "/usr/local/airflow/.local/lib/python3.11/site-packages/datahub_airflow_plugin/_extractors.py", line 171, in _sql_extractor_extract
    sql = self.operator.sql
          ^^^^^^^^^^^^^^^^^
AttributeError: 'AthenaOperator' object has no attribute 'sql'
```

**To Reproduce**
Create an Airflow dag using the AthenaOperator and run it while having acryl-datahub-airflow-plugin[plugin-v2]==0.13.3.4 set up. 

**Expected behavior**
I'd expect the plugin to extract the lineage information from the correct field, probably the field query. 

**Additional context**
The version I am using:
apache-airflow 2.8.1
acryl-datahub-airflow-plugin[plugin-v2]==0.13.3.4

### PR DESCRIPTION
**Pull request by steffengr**
The GenericSqlExtractor which is currently by the DataHub Airflow plugin to extract lineage information does not properly support the AthenaOperator and crashes with "AttributeError: 'AthenaOperator' object has no attribute 'sql'". This patch introduces a AthenaOperatorExtractor following the BigQueryInsertJobOperatorExtractor example to fix support for the AthenaOperator.

Fixes #11160 

## Checklist

- [x] The PR conforms to DataHub's [Contributing Guideline](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [x] Links to related issues (if applicable)
- [x] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable). If a new feature has been added a Usage Guide has been added for the same.
- [ ] For any breaking change/potential downtime/deprecation/big changes an entry has been made in [Updating DataHub](https://github.com/datahub-project/datahub/blob/master/docs/how/updating-datahub.md)

### CODE REVIEW

**Review by hsheth2 — COMMENTED** [review]
The code looks reasonable - can we add a test for this?

**Comment by steffengr** [comment]
@hsheth2 Thank for looking at this! I don't see related tests in this module. Could you point me at an example? I don't have much experience with this code base.

**Comment by hsheth2** [comment]
@steffengr we have an integration test (https://github.com/datahub-project/datahub/blob/master/metadata-ingestion-modules/airflow-plugin/tests/integration/test_plugin.py) that runs a number of DAGs (e.g. https://github.com/datahub-project/datahub/blob/master/metadata-ingestion-modules/airflow-plugin/tests/integration/dags/snowflake_operator.py)

That'd probably be the easiest way to do it. Otherwise, we could also do a more targeted unit test in https://github.com/datahub-project/datahub/blob/master/metadata-ingestion-modules/airflow-plugin/tests/unit/test_airflow.py

**Comment by steffengr** [comment]
@hsheth2 I added a test. I had to set `"AIRFLOW__API__AUTH_BACKENDS": "airflow.providers.fab.auth_manager.api.auth.backend.basic_auth",` to get these tests to work. Probably some change in Airflow.

**Comment by steffengr** [comment]
I'm not sure what causes these test failures. I'm also getting them on master.

**Comment by hsheth2** [comment]
Looks like CI is still failing. I see this in the logs (e.g. here https://github.com/datahub-project/datahub/actions/runs/12052943048/job/33607437487?pr=11857)
```
Traceback (most recent call last):
  File "/home/runner/work/datahub/datahub/metadata-ingestion-modules/airflow-plugin/venv/bin/airflow", line 8, in <module>
    sys.exit(main())
  File "/home/runner/work/datahub/datahub/metadata-ingestion-modules/airflow-plugin/venv/lib/python3.10/site-packages/airflow/__main__.py", line 57, in main
    args.func(args)
  File "/home/runner/work/datahub/datahub/metadata-ingestion-modules/airflow-plugin/venv/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/runner/work/datahub/datahub/metadata-ingestion-modules/airflow-plugin/venv/lib/python3.10/site-packages/airflow/utils/cli.py", line 114, in wrapper
    return f(*args, **kwargs)
  File "/home/runner/work/datahub/datahub/metadata-ingestion-modules/airflow-plugin/venv/lib/python3.10/site-packages/airflow/utils/providers_configuration_loader.py", line 55, in wrapped_function
    return func(*args, **kwargs)
  File "/home/runner/work/datahub/datahub/metadata-ingestion-modules/airflow-plugin/venv/lib/python3.10/site-packages/airflow/cli/commands/dag_command.py", line 160, in dag_trigger
    message = api_client.trigger_dag(
  File "/home/runner/work/datahub/datahub/metadata-ingestion-modules/airflow-plugin/venv/lib/python3.10/site-packages/airflow/api/client/local_client.py", line 34, in trigger_dag
    dag_run = trigger_dag.trigger_dag(
  File "/home/runner/work/datahub/datahub/metadata-ingestion-modules/airflow-plugin/venv/lib/python3.10/site-packages/airflow/api/common/trigger_dag.py", line 119, in trigger_dag
    raise DagNotFound(f"Dag id {dag_id} not found in DagModel")
airflow.exceptions.DagNotFound: Dag id athena_operator not found in DagModel
```

I also created https://github.com/datahub-project/datahub/pull/11981 to help make this a bit easier to debug, in case that's useful.

**Comment by steffengr** [comment]
@hsheth2 I'm lost here. I suspected there might be a race condition between triggering the dag and loading it as I get this error randomly on any of the test dags on my local machine. However, calling the rest API to wait for the dag to be available doesn't seem to help on some of the Airflow versions. Any idea what could cause the dag to not load on some of the Airflow versions?

**Comment by hsheth2** [comment]
@steffengr with airflow 2.4, we support a limited form of the plugin, since certain features weren't available until later versions.

We run tests for that as well, which generates the "no_dag_listener" variants of the golden files. That file golden can only be generated on airflow 2.4.

I believe something like this would generate that missing file.
```
tox -e py310-airflow24 -- 'tests/integration/test_plugin.py::test_airflow_plugin[v2_athena_operator_no_dag_listener]' --update-golden-files
```

**Comment by steffengr** [comment]
@hsheth2 Thanks! That did the trick. Is there any chance to get this into a 0.14 patch release?

**Review by hsheth2 — APPROVED** [review]

**Pull request merged**
