### PR TITLE
fix(profile): bigquery-legacy - Fix for TypeError-related failures in legacy plugin

### PR DESCRIPTION
**Pull request by senapatim**
In version 0.9.3, we see the following error for data-profiling on bigquery tables:
` File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/datahub/ingestion/source/sql/bigquery.py", line 799, in get_latest_partition
    return BigQueryPartitionColumn(**row.items())
TypeError: type object argument after ** must be a mapping, not list`

It seems like the update was made in a recent push, which resulted in failure of jobs while using the `bigquery-legacy` plugin.

I've tested this change in version 0.9.3 and the ingestion pipleline with data profiling finished successfully.

## Checklist

- [ ] The PR conforms to DataHub's [Contributing Guideline](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [ ] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable). If a new feature has been added a Usage Guide has been added for the same.
- [ ] For any breaking change/potential downtime/deprecation/big changes an entry has been made in [Updating DataHub](https://github.com/datahub-project/datahub/blob/master/docs/how/updating-datahub.md)

### CODE REVIEW

**Review by hsheth2 — APPROVED** [review]

**Review by treff7es — APPROVED** [review]
lgtm

**Review by feljen — APPROVED** [review]

**Comment by jjoyce0510** [comment]
Looks like this is failing lint!

**Comment by senapatim** [comment]
> Looks like this is failing lint!

Is there some other way to see the exact line causing a lint failure? The [logs](https://github.com/datahub-project/datahub/actions/runs/3733759825/jobs/6335738951) point to unit test functions.

**Comment by hsheth2** [comment]
@senapatim I believe the lint failure was unrelated. John merged in `master` which should resolve it

**Comment by senapatim** [comment]
Thank you so much @hsheth2 and @jjoyce0510 !

**Comment by jjoyce0510** [comment]
Will merge once green. Thanks for the contrib!

**Pull request merged**
