### PR TITLE
Advance search - Added case sensitive flag for wildcard searches

### PR DESCRIPTION
**Pull request by kanavnarula**
Current global text search on browse page brings case insensitive results. With advance filters added, search becomes case sensitive. 

Adding caseInsensitive param to help get all results with wildcard searches.

## Checklist

- [ ] The PR conforms to DataHub's [Contributing Guideline](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [ ] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable). If a new feature has been added a Usage Guide has been added for the same.
- [ ] For any breaking change/potential downtime/deprecation/big changes an entry has been made in [Updating DataHub](https://github.com/datahub-project/datahub/blob/master/docs/how/updating-datahub.md)

### CODE REVIEW

**Review by david-leifker — APPROVED** [review]
lgtm!

**Comment by david-leifker** [comment]
```
> The following files had format violations:
      src/main/java/com/linkedin/metadata/search/utils/ESUtils.java
          @@ -582,7 +582,8 @@
           ··········QueryBuilders.wildcardQuery(
           ··················toKeywordField(criterion.getField(),·isTimeseries,·aspectRetriever),
           ··················String.format(wildcardPattern,·ESUtils.escapeReservedCharacters(value.trim())))
          -··············.queryName(queryName·!=·null·?·queryName·:·fieldName).caseInsensitive(true));
          +··············.queryName(queryName·!=·null·?·queryName·:·fieldName)
          +··············.caseInsensitive(true));
           ····}
           ····return·boolQuery;
           ··}
  Run './gradlew :metadata-io:spotlessApply' to fix these violations.
```

ptal @kanavnarula

**Comment by kanavnarula** [comment]
> c600aa5

This is taken care @david-leifker . Thanks!

**Comment by kanavnarula** [comment]
> ```
> > The following files had format violations:
>       src/main/java/com/linkedin/metadata/search/utils/ESUtils.java
>           @@ -582,7 +582,8 @@
>            ··········QueryBuilders.wildcardQuery(
>            ··················toKeywordField(criterion.getField(),·isTimeseries,·aspectRetriever),
>            ··················String.format(wildcardPattern,·ESUtils.escapeReservedCharacters(value.trim())))
>           -··············.queryName(queryName·!=·null·?·queryName·:·fieldName).caseInsensitive(true));
>           +··············.queryName(queryName·!=·null·?·queryName·:·fieldName)
>           +··············.caseInsensitive(true));
>            ····}
>            ····return·boolQuery;
>            ··}
>   Run './gradlew :metadata-io:spotlessApply' to fix these violations.
> ```
> 
> ptal @kanavnarula

This is taken care @david-leifker . Please take a look once again. Thanks!

**Comment by david-leifker** [comment]
Getting close now, 3 failed tests in metadata-io
```
metadata-io > nonsearch > com.linkedin.metadata.search.utils.ESUtilsTest > testGetQueryBuilderFromCriterionContain FAILED
    java.lang.AssertionError: expected [{
      "wildcard" : {
        "myTestField.keyword" : {
          "wildcard" : "*value1*",
          "boost" : 1.0,
          "_name" : "myTestField"
        }
      }
    }] but found [{
      "wildcard" : {
        "myTestField.keyword" : {
          "wildcard" : "*value1*",
          "case_insensitive" : true,
          "boost" : 1.0,
          "_name" : "myTestField"
        }
      }
    }]
        at org.testng.Assert.fail(Assert.java:111)
        at org.testng.Assert.failNotEquals(Assert.java:1578)
        at org.testng.Assert.assertEqualsImpl(Assert.java:150)
        at org.testng.Assert.assertEquals(Assert.java:132)
        at org.testng.Assert.assertEquals(Assert.java:656)
        at org.testng.Assert.assertEquals(Assert.java:666)
        at com.linkedin.metadata.search.utils.ESUtilsTest.testGetQueryBuilderFromCriterionContain(ESUtilsTest.java:186)

metadata-io > nonsearch > com.linkedin.metadata.search.utils.ESUtilsTest > testWildcardQueryBuilderFromCriterionWhenEndsWith FAILED
    java.lang.AssertionError: expected [{
      "wildcard" : {
        "myTestField.keyword" : {
          "wildcard" : "*value1",
          "boost" : 1.0,
          "_name" : "myTestField"
        }
      }
    }] but found [{
      "wildcard" : {
        "myTestField.keyword" : {
          "wildcard" : "*value1",
          "case_insensitive" : true,
          "boost" : 1.0,
          "_name" : "myTestField"
        }
      }
    }]
        at org.testng.Assert.fail(Assert.java:111)
        at org.testng.Assert.failNotEquals(Assert.java:1578)
        at org.testng.Assert.assertEqualsImpl(Assert.java:150)
        at org.testng.Assert.assertEquals(Assert.java:132)
        at org.testng.Assert.assertEquals(Assert.java:656)
        at org.testng.Assert.assertEquals(Assert.java:666)
        at com.linkedin.metadata.search.utils.ESUtilsTest.testWildcardQueryBuilderFromCriterionWhenEndsWith(ESUtilsTest.java:330)

metadata-io > nonsearch > com.linkedin.metadata.search.utils.ESUtilsTest > testWildcardQueryBuilderFromCriterionWhenStartsWith FAILED
    java.lang.AssertionError: expected [{
      "wildcard" : {
        "myTestField.keyword" : {
          "wildcard" : "value1*",
          "boost" : 1.0,
          "_name" : "myTestField"
        }
      }
    }] but found [{
      "wildcard" : {
        "myTestField.keyword" : {
          "wildcard" : "value1*",
          "case_insensitive" : true,
          "boost" : 1.0,
          "_name" : "myTestField"
        }
      }
    }]
        at org.testng.Assert.fail(Assert.java:111)
        at org.testng.Assert.failNotEquals(Assert.java:1578)
        at org.testng.Assert.assertEqualsImpl(Assert.java:150)
        at org.testng.Assert.assertEquals(Assert.java:132)
        at org.testng.Assert.assertEquals(Assert.java:656)
        at org.testng.Assert.assertEquals(Assert.java:666)
        at com.linkedin.metadata.search.utils.ESUtilsTest.testWildcardQueryBuilderFromCriterionWhenStartsWith(ESUtilsTest.java:260)
```

**Comment by kanavnarula** [comment]
> Getting close now, 3 failed tests in metadata-io
> 
> ```
> metadata-io > nonsearch > com.linkedin.metadata.search.utils.ESUtilsTest > testGetQueryBuilderFromCriterionContain FAILED
>     java.lang.AssertionError: expected [{
>       "wildcard" : {
>         "myTestField.keyword" : {
>           "wildcard" : "*value1*",
>           "boost" : 1.0,
>           "_name" : "myTestField"
>         }
>       }
>     }] but found [{
>       "wildcard" : {
>         "myTestField.keyword" : {
>           "wildcard" : "*value1*",
>           "case_insensitive" : true,
>           "boost" : 1.0,
>           "_name" : "myTestField"
>         }
>       }
>     }]
>         at org.testng.Assert.fail(Assert.java:111)
>         at org.testng.Assert.failNotEquals(Assert.java:1578)
>         at org.testng.Assert.assertEqualsImpl(Assert.java:150)
>         at org.testng.Assert.assertEquals(Assert.java:132)
>         at org.testng.Assert.assertEquals(Assert.java:656)
>         at org.testng.Assert.assertEquals(Assert.java:666)
>         at com.linkedin.metadata.search.utils.ESUtilsTest.testGetQueryBuilderFromCriterionContain(ESUtilsTest.java:186)
> 
> metadata-io > nonsearch > com.linkedin.metadata.search.utils.ESUtilsTest > testWildcardQueryBuilderFromCriterionWhenEndsWith FAILED
>     java.lang.AssertionError: expected [{
>       "wildcard" : {
>         "myTestField.keyword" : {
>           "wildcard" : "*value1",
>           "boost" : 1.0,
>           "_name" : "myTestField"
>         }
>       }
>     }] but found [{
>       "wildcard" : {
>         "myTestField.keyword" : {
>           "wildcard" : "*value1",
>           "case_insensitive" : true,
>           "boost" : 1.0,
>           "_name" : "myTestField"
>         }
>       }
>     }]
>         at org.testng.Assert.fail(Assert.java:111)
>         at org.testng.Assert.failNotEquals(Assert.java:1578)
>         at org.testng.Assert.assertEqualsImpl(Assert.java:150)
>         at org.testng.Assert.assertEquals(Assert.java:132)
>         at org.testng.Assert.assertEquals(Assert.java:656)
>         at org.testng.Assert.assertEquals(Assert.java:666)
>         at com.linkedin.metadata.search.utils.ESUtilsTest.testWildcardQueryBuilderFromCriterionWhenEndsWith(ESUtilsTest.java:330)
> 
> metadata-io > nonsearch > com.linkedin.metadata.search.utils.ESUtilsTest > testWildcardQueryBuilderFromCriterionWhenStartsWith FAILED
>     java.lang.AssertionError: expected [{
>       "wildcard" : {
>         "myTestField.keyword" : {
>           "wildcard" : "value1*",
>           "boost" : 1.0,
>           "_name" : "myTestField"
>         }
>       }
>     }] but found [{
>       "wildcard" : {
>         "myTestField.keyword" : {
>           "wildcard" : "value1*",
>           "case_insensitive" : true,
>           "boost" : 1.0,
>           "_name" : "myTestField"
>         }
>       }
>     }]
>         at org.testng.Assert.fail(Assert.java:111)
>         at org.testng.Assert.failNotEquals(Assert.java:1578)
>         at org.testng.Assert.assertEqualsImpl(Assert.java:150)
>         at org.testng.Assert.assertEquals(Assert.java:132)
>         at org.testng.Assert.assertEquals(Assert.java:656)
>         at org.testng.Assert.assertEquals(Assert.java:666)
>         at com.linkedin.metadata.search.utils.ESUtilsTest.testWildcardQueryBuilderFromCriterionWhenStartsWith(ESUtilsTest.java:260)
> ```

Thanks for sharing @david-leifker ! Updated the test cases and committed. Please take a look when you get time

**Comment by david-leifker** [comment]
LGTM! Thank you!

**Comment by kanavnarula** [comment]
Thanks @david-leifker!

**Pull request merged**
