### PR TITLE
refactor(java11) - convert most modules to java 11

### PR DESCRIPTION
**Pull request by leifker**
This PR is one of two Java 11 options ([other](https://github.com/datahub-project/datahub/pull/5835)) - **only merge one**. This version converts modules to Java 11 where they are not tied to spark-lineage which requires Java 8. Unlike the other PR, there are no duplicate modules for Java 11 and Java 8, only one java version is chosen based on its usage by `spark-lineage`

All modules except these are converted to java 11:

li-utils
metadata-models
test-models
metadata-integration:java:datahub-client
metadata-integration:java:spark-lineage

## Checklist
- [x] The PR conforms to DataHub's [Contributing Guideline](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [x] Links to related issues (if applicable)
- [x] Tests for the changes have been added/updated (if applicable)
- [x] Docs related to the changes have been added/updated (if applicable). If a new feature has been added a Usage Guide has been added for the same.
- [x] For any breaking change/potential downtime/deprecation/big changes an entry has been made in [Updating DataHub](https://github.com/datahub-project/datahub/blob/master/docs/how/updating-datahub.md)

### CODE REVIEW

**Comment by pedro93** [comment]
Hello @leifker 

Thank you for tackling this large effort! It seems you have some failing checks in CI. The spark smoke tests seem to be real, the rest are flakes.

More generally...
What is the intended objective with this PR (or it's alternative)? 

We have another smaller, more contained PR that is intended to upgrade the java runtime for all DataHub's components to Java 11 with the objective of making our images more cloud native and use more recent optimisations.
Is this your intended goal? If not, could you please elaborate?

**Comment by leifker** [comment]
> Hello @leifker
> 
> Thank you for tackling this large effort! It seems you have some failing checks in CI. The spark smoke tests seem to be real, the rest are flakes.
> 
> More generally... What is the intended objective with this PR (or it's alternative)?
> 
> We have another smaller, more contained PR that is intended to upgrade the java runtime for all DataHub's components to Java 11 with the objective of making our images more cloud native and use more recent optimisations. Is this your intended goal? If not, could you please elaborate?

@pedro93 - The intent is to build any, or all, modules with jdk11. The docker images would need to updated to jdk11 as a requirement to run the jars generated with jdk11. Only certain modules would require jdk8, specifically those for supporting `spark-lineage`. For this later case, those specific modules can either be compile for jdk8 or for both jdk8 and jdk11 (this is the difference between the two PRs).

The failing tests seem related to other changes to the browse path that are outside of these changes. I will make a few updates to get the tests to pass and continue to update with the main branch to incorporate on-going changes. There is a thread [here](https://datahubspace.slack.com/archives/C029A3M079U/p1662734505130089) which outlines what I see with respect to changing browse paths (which occurs in the main branch).

**Comment by pedro93** [comment]
```
@pedro93 - The intent is to build any, or all, modules with jdk11. The docker images would need to updated to jdk11 as a requirement to run the jars generated with jdk11. Only certain modules would require jdk8, specifically those for supporting spark-lineage. For this later case, those specific modules can either be compile for jdk8 or for both jdk8 and jdk11 (this is the difference between the two PRs).
```

My question is more, what is the benefit of compiling datahub code with java 11 jdk? byte code improvements? Java 11 language features?

Following https://github.com/datahub-project/datahub/pull/5875 all datahub images will run in Java 11 runtime with java 8 byte code.

**Comment by leifker** [comment]
There are a couple benefits of compiling with jdk11 where possible. 

One of them are language features for sure. For example, `:metadata-integration:java:datahub-protobuf`, in the project is using jdk11 and is not compatible with jdk8. I wrote that module before realizing the jdk8 dependence of the project.

I think that the most important reason is ultimately that many libraries are deprecating jdk8 support and without updating to jdk11 this locks DataHub into older versions of libraries. In turn, these older libraries may not contain important security fixes and newer functionality.

**Review by shirshanka — APPROVED** [review]
LGTM!

**Pull request merged**
