### PR TITLE
ci(ingest): test with python 3.11

### PR DESCRIPTION
**Pull request by hsheth2**
## Checklist

- [ ] The PR conforms to DataHub's [Contributing Guideline](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [ ] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable). If a new feature has been added a Usage Guide has been added for the same.
- [ ] For any breaking change/potential downtime/deprecation/big changes an entry has been made in [Updating DataHub](https://github.com/datahub-project/datahub/blob/master/docs/how/updating-datahub.md)

### CODE REVIEW

**Comment by jjoyce0510** [comment]
Hi there! We are trying to move aware from "env" as a concept in DataHub (deprecating it).

is there a strong reason you want to use the env, as opposed Data Platform Instance (recommended) going forward?

**Comment by hsheth2** [comment]
Now blocked on https://github.com/googleapis/python-bigquery-sqlalchemy/pull/543

**Review by anshbansal — APPROVED** [review]
LGTM once CI is green

**Comment by anshbansal** [comment]
Looks all tests are failing now.

**Comment by hsheth2** [comment]
Blocked because of https://github.com/feast-dev/feast/issues/3510

**Comment by hsheth2** [comment]
No longer blocked on feast.

Now we're blocked on https://github.com/cloudera/python-sasl/issues/30 (we actually use sasl3 and not sasl but they face the same issue). We only depend on sasl3 from acryl-pyhive, so we probably could upgrade it to use pure-sasl instead. There seems to be an effort around that already https://github.com/dropbox/PyHive/pull/454.

**Comment by hsheth2** [comment]
Just need to merge https://github.com/acryldata/PyHive/pull/7 and update here, and then we should be good to go.

**Comment by mdeshmu** [comment]
@hsheth2 

I made a couple of contributions to PyHive which were accepted and released in [0.7.1.dev0](https://pypi.org/project/PyHive/0.7.1.dev0/). You are requested to test with the dev version and report any bugs in the PyHive GitHub repository before 0.7.1 is released in a month or so. 

1. PyHive also supports [pure-sasl](https://pypi.org/project/pure-sasl/) via additional extras 'pyhive[hive_pure_sasl]' which supports Python 3.11 in addition to previous Python versions. See https://github.com/dropbox/PyHive/pull/454
2. PyHive is now compatible with SQLAlchemy 2.0. See https://github.com/dropbox/PyHive/pull/457

**Comment by hsheth2** [comment]
Looks like there's two errors now:
1. PowerBI using a mutable type for a dataclass default
2. Something related to typing (with snowflake?), similar to https://github.com/python/cpython/issues/100316

**Comment by hsheth2** [comment]
- The powerbi issue will be fixed by https://github.com/datahub-project/datahub/pull/8609
- Looks like the CodeType error is from pyspark and fixed in recent versions, so we just need to upgrade: blocked on #6908 
- There's also an issue with the ratelimiter package - we'll need to find an alternative because the project looks dead: https://github.com/RazerM/ratelimiter/issues/18

**Comment by hsheth2** [comment]
Unblocked now that https://github.com/datahub-project/datahub/pull/9008 was merged

**Comment by hsheth2** [comment]
One more thing here: To be compatible with Python 3.11, we need to be on pyspark 3.4+ (see https://github.com/apache/spark/pull/38987)

However, pydeequ still depends on pyspark 3.3 right now (https://github.com/awslabs/python-deequ/pull/168). The underlying deequ issue was recently fixed (https://github.com/awslabs/deequ/pull/505), so pydeequ will hopefully get updated quickly.

**Comment by hsheth2** [comment]
Moving the StrEnum changes to https://github.com/datahub-project/datahub/pull/11270

**Comment by hsheth2** [comment]
Closing in favor of https://github.com/datahub-project/datahub/pull/11280

**Pull request closed without merging**
