### PR TITLE
feat(ui) - added panel to track change events of dataset

### PR DESCRIPTION
**Pull request by neojunjie**
## Checklist

- [ ] The PR conforms to DataHub's [Contributing Guideline](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [ ] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable). If a new feature has been added a Usage Guide has been added for the same.
- [ ] For any breaking change/potential downtime/deprecation/big changes an entry has been made in [Updating DataHub](https://github.com/datahub-project/datahub/blob/master/docs/how/updating-datahub.md)

Currently, there is no easy way (visually) for anyone (consumers, owners, producers) to keep track of what is going on with the dataset. This PR will add a new panel to display all the changes related to the dataset.

### CODE REVIEW

**Comment by neojunjie** [comment]
[https://files.slack.com/files-pri/TUMKD5EGJ-F049MEW47RN/change_events2.png](url)

**Comment by maggiehays** [comment]
Pulling screenshots from Slack conversation 

change_events
change_events2

**Comment by jjoyce0510** [comment]
Hi guys! 

First of all, awesome work! I'm really excited to see this feature come to fruition. We've gone long enough without :).

The UI for this pass is a great starting point. Where we are hoping to go is something like the following:

Screen Shot 2022-11-01 at 4 07 03 PM

Where each activity entry has rich content, ability to select entities, and more. Is this something you are willing to work with us to get to? 

We're happy to provide support and further clarity where possible. 

Cheers,
John

**Comment by neojunjie** [comment]
Hi all

Sure. Willing to work with you guys to move to the desired state.

**Comment by jjoyce0510** [comment]
Let us know if you need any support here :)

**Comment by neojunjie** [comment]
Hi John

I will be away for 2 weeks.

**Comment by aditya-radhakrishnan** [comment]
Hi @neojunjie let us know when you're planning on picking this up again!

**Comment by aditya-radhakrishnan** [comment]
Going to close this PR until this is ready to be picked up again. Please feel free to reopen @neojunjie!

**Comment by aditya-radhakrishnan** [comment]
Also happy to work with you to get this to the finish line!

**Pull request closed without merging**
