### PR TITLE
fix(elasticsearch-client): allow connection to external Elasticsearch instance via proxy

### PR DESCRIPTION
**Pull request by haeniya**
We're running Datahub behind a proxy and need it to talk to an external Elasticsearch instance. To allow this, we needed to add this change to the Elasticsearch client that tells it to take system properties like http.proxyHost, https.proxyHost or http.nonProxyHosts into account.

Note: I think this client is used in both datahub-gms and datahub-upgrade.

## Checklist

- [x] The PR conforms to DataHub's [Contributing Guideline](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [x] Links to related issues (if applicable)
- [x] Tests for the changes have been added/updated (if applicable)
- [x] Docs related to the changes have been added/updated (if applicable). If a new feature has been added a Usage Guide has been added for the same.
- [x] For any breaking change/potential downtime/deprecation/big changes an entry has been made in [Updating DataHub](https://github.com/datahub-project/datahub/blob/master/docs/how/updating-datahub.md)

### CODE REVIEW

**Review by david-leifker — APPROVED** [review]

**Comment by david-leifker** [comment]
Please run `./gradlew spotlessApply` and we can get this merged! Thanks!

**Comment by haeniya** [comment]
> Please run `./gradlew spotlessApply` and we can get this merged! Thanks!

@david-leifker I tried to run `./gradlew spotlessApply` but got the following error message:
```
To honour the JVM settings for this build a single-use Daemon process will be forked. See https://docs.gradle.org/8.0.2/userguide/gradle_daemon.html#sec:disabling_the_daemon.
Daemon will be stopped at the end of the build 
Configuration on demand is an incubating feature.

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'datahub-github'.
> Could not resolve all files for configuration ':classpath'.
   > Could not resolve org.springframework.boot:spring-boot-gradle-plugin:3.2.1.
     Required by:
         project :
      > No matching variant of org.springframework.boot:spring-boot-gradle-plugin:3.2.1 was found. The consumer was configured to find a library for use during runtime, compatible with Java 11, packaged as a jar, and its dependencies declared externally, as well as attribute 'org.gradle.plugin.api-version' with value '8.0.2' but:
          - Variant 'apiElements' capability org.springframework.boot:spring-boot-gradle-plugin:3.2.1 declares a library, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares a component for use during compile-time, compatible with Java 17 and the consumer needed a component for use during runtime, compatible with Java 11
              - Other compatible attribute:
                  - Doesn't say anything about org.gradle.plugin.api-version (required '8.0.2')
          - Variant 'javadocElements' capability org.springframework.boot:spring-boot-gradle-plugin:3.2.1 declares a component for use during runtime, and its dependencies declared externally:
              - Incompatible because this component declares documentation and the consumer needed a library
              - Other compatible attributes:
                  - Doesn't say anything about its target Java version (required compatibility with Java 11)
                  - Doesn't say anything about its elements (required them packaged as a jar)
                  - Doesn't say anything about org.gradle.plugin.api-version (required '8.0.2')
          - Variant 'mavenOptionalApiElements' capability org.springframework.boot:spring-boot-gradle-plugin-maven-optional:3.2.1 declares a library, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares a component for use during compile-time, compatible with Java 17 and the consumer needed a component for use during runtime, compatible with Java 11
              - Other compatible attribute:
                  - Doesn't say anything about org.gradle.plugin.api-version (required '8.0.2')
          - Variant 'mavenOptionalRuntimeElements' capability org.springframework.boot:spring-boot-gradle-plugin-maven-optional:3.2.1 declares a library for use during runtime, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares a component, compatible with Java 17 and the consumer needed a component, compatible with Java 11
              - Other compatible attribute:
                  - Doesn't say anything about org.gradle.plugin.api-version (required '8.0.2')
          - Variant 'runtimeElements' capability org.springframework.boot:spring-boot-gradle-plugin:3.2.1 declares a library for use during runtime, packaged as a jar, and its dependencies declared externally:
              - Incompatible because this component declares a component, compatible with Java 17 and the consumer needed a component, compatible with Java 11
              - Other compatible attribute:
                  - Doesn't say anything about org.gradle.plugin.api-version (required '8.0.2')
          - Variant 'sourcesElements' capability org.springframework.boot:spring-boot-gradle-plugin:3.2.1 declares a component for use during runtime, and its dependencies declared externally:
              - Incompatible because this component declares documentation and the consumer needed a library
              - Other compatible attributes:
                  - Doesn't say anything about its target Java version (required compatibility with Java 11)
                  - Doesn't say anything about its elements (required them packaged as a jar)
                  - Doesn't say anything about org.gradle.plugin.api-version (required '8.0.2')
```

Any idea what I need to do here?

**Review by darnaut — CHANGES_REQUESTED** [review]
Having these as  actual datahub properties would work better for the project compared to loading from system props. There's a few components that talk to ES and having them as datahub properties would allow us to hook them up to the right containers/components. For example, setting `global.elasticsearch.proxy` in a Helm chart would allows us to propagate it to every container that needs it, instead of relying on users to figure that out and set the env vars for each individual component.

Ref Elasticsearch options: https://github.com/datahub-project/datahub/blob/3bfc1e4/metadata-service/configuration/src/main/resources/application.yml#L159

Also for completeness, the elasticsearch-setup job would need changes too https://github.com/datahub-project/datahub/tree/master/docker/elasticsearch-setup

**Comment by haeniya** [comment]
> Having these as actual datahub properties would work better for the project compared to loading from system props. There's a few components that talk to ES and having them as datahub properties would allow us to hook them up to the right containers/components. For example, setting `global.elasticsearch.proxy` in a Helm chart would allows us to propagate it to every container that needs it, instead of relying on users to figure that out and set the env vars for each individual component.
> 
> Ref Elasticsearch options: https://github.com/datahub-project/datahub/blob/3bfc1e4/metadata-service/configuration/src/main/resources/application.yml#L159
> 
> Also for completeness, the elasticsearch-setup job would need changes too https://github.com/datahub-project/datahub/tree/master/docker/elasticsearch-setup

Hi @darnaut, thanks for your feedback. Here are my thoughts about it:
 
- It's not only about Elasticsearch. We need to define the proxy settings in the Java opts anyway (e.g. for the Kafka schema registry). This one-liner just makes sure that also the Elasticsearch client respects those values. So instead of defining the proxy for the different services (e.g. Elasticsearch, Kafka) specifically, we just need to define it in the Java opts and things work.
 
- What we could do in the future, maybe, is having a central place in the Helm chart where people can configure the proxy settings for all the containers. But we would need to make sure that all images accept ENV vars that are used to correctly define the proxy settings for the Java process internally. However, we would still need the changes proposed in this PR and I think this would require quite some alignment and refactoring for different images to make things consistent. For example, in GMS, it seems that people can set `JAVA_OPTS` to define Java opts including the proxy settings. In the frontend, proxy settings can be defined specifically with variables like HTTP_NON_PROXY_HOSTS or HTTP_PROXY_HOST.
 
For now, I'd personally keep the changes as proposed. It's a one-liner that gives people the ability to connect to an external Elasticsearch via proxy. What do you think?
 
PS: The elasticsearch-setup job doesn't seem to be affected by this. We're able to run it successfully with the standard image provided by Acryl and didn't have to build a custom image for it. It's just a shell script that runs a bunch of curl commands against Elasticsearch, so it doesn't need any Java opts but probably looks at the standard ENV vars related to the proxy.

**Comment by darnaut** [comment]
> It's not only about Elasticsearch. We need to define the proxy settings in the Java opts anyway (e.g. for the Kafka schema registry). This one-liner just makes sure that also the Elasticsearch client respects those values. So instead of defining the proxy for the different services (e.g. Elasticsearch, Kafka) specifically, we just need to define it in the Java opts and things work.

But that's exactly the issue I'm concerned. It applies to everything that uses `RestHighLevelClient`, which today might only be (e.g. Elasticsearch, Kafka) but there's no guarantee it won't be used for other internal requests in the future. That's why I'm saying it's much better to make these choices (whether to use proxy) explicit. Right now this one line is gonna be basically invisible to most if not all developers working on Datahub and things might break in weird ways that will also cause issues for us if, for example, someone asks for support/help.

Just to reiterate, whether the proxy configuration in the Datahub configuration is global (applies to all external services) or service specific (e.g. kafka), that's fine either way. My suggestion is that having these as actual Datahub properties would work better for the project compared to loading from system props.

> For now, I'd personally keep the changes as proposed. It's a one-liner that gives people the ability to connect to an external Elasticsearch via proxy. What do you think?

If users come to rely on it, changing it later would be breaking existing setups. Also same issue without this change, some user might have HTTP_PROXY set for other reasons and this will break it.

Also this is not much additional work, you just need to add the required Datahub properties.

**Comment by haeniya** [comment]
> But that's exactly the issue I'm concerned. It applies to everything that uses `RestHighLevelClient`, which today might only be (e.g. Elasticsearch, Kafka) but there's no guarantee it won't be used for other internal requests in the future. That's why I'm saying it's much better to make these choices (whether to use proxy) explicit. Right now this one line is gonna be basically invisible to most if not all developers working on Datahub and things might break in weird ways that will also cause issues for us if, for example, someone asks for support/help.
> 
> Just to reiterate, whether the proxy configuration in the Datahub configuration is global (applies to all external services) or service specific (e.g. kafka), that's fine either way. My suggestion is that having these as actual Datahub properties would work better for the project compared to loading from system props.
> 
> If users come to rely on it, changing it later would be breaking existing setups. Also same issue w/ this change, some user might have HTTP_PROXY set for other reasons and this will break it.
> 
> Also this is not much additional work, you just need to add the required Datahub properties.

@darnaut, the `RestHighLevelClient` comes from the Elasticsearch/Opensearch library and is exclusively used for Elasticsearch. See the import statement `import org.opensearch.client.RestHighLevelClient`.
Other clients, e.g. for Kafka already respect the proxy settings passed to the Java process (at least we didn't have any issues there). This one-liner only makes sure that also the Elasticsearch client respects them.

Usually, from my experience, when defining proxy settings developers do the following:
- Specify standard ENV vars like `HTTP_PROXY`, `HTTPS_PROXY`, `NO_PROXY` for things like curl commands that operate on a operating system level and are not specific to Java.
- For Java applications it is common to add Java specific system properties like `http.proxyHost`, `http.proxyPort` or `http.nonProxyHosts`. This is a known practice for developers to define proxy settings, and it's not "invisible". Also, this change should not cause Datahub to "break in weird ways" as it only affects people that specifically define their proxy in the Java system properties. The current issue in Datahub is, that these standard Java specific system properties are not respected by the Elasticsearch client (and only this client), which is why it's basically failing in "weird ways" right now.

It's perfectly fine (and mostly done) to define ENV vars like `HTTP_PROXY` and the Java specific system properties at the same time. This will not break anything.

So in my opinion, it doesn't really make sense to put this as Datahub properties. These Java system properties are set when starting the Java application, and we don't have any Datahub properties at this point.
We could define proxy related Datahub properties and then configure the proxy manually for all the different clients within the code, but that would be way more effort and requires deep knowledge of the whole Datahub codebase.

If this change is a deal-breaker for you guys, we can also close this PR, and we'll keep using custom images for now. Let me know what you think.

**Pull request closed without merging**
