### PR TITLE
feat(ingestion): For all usage connectors, allow exclusion of top_n_queries from ingestion via a config param.

### PR DESCRIPTION
**Pull request by BoyuanZhangDE**
## Checklist
- [x] The PR conforms to DataHub's [Contributing Guideline](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [x] Links to related issues (if applicable)
- [x] Tests for the changes have been added/updated (if applicable)
- [x] Docs related to the changes have been added/updated (if applicable). If a new feature has been added a Usage Guide has been added for the same.
- [x] For any breaking change/potential downtime/deprecation/big changes an entry has been made in [Updating DataHub](https://github.com/datahub-project/datahub/blob/master/docs/how/updating-datahub.md)

### CODE REVIEW

**Comment by BoyuanZhangDE** [comment]
- Allow users to set `display_top_sql_queries` as `false` to not display the queries in the UI. 
- This is because we found the queries could expose sensitive data

**Review by BoyuanZhangDE — COMMENTED** [review]
Change `exclude_top_sql_queries` to `include_top_n_queries` to in line with the existing `include_operational_stats`

**Review by BoyuanZhangDE — COMMENTED** [review]
changed `exclude_top_sql_queries` to `include_top_n_queries`

**Review by BoyuanZhangDE — COMMENTED** [review]
changed the name of `exclude_top_sql_queries`

**Review by BoyuanZhangDE — COMMENTED** [review]
changed

**Review by BoyuanZhangDE — COMMENTED** [review]
changed from exclude to include

**Review by rslanka — APPROVED** [review]
LGTM!

**Pull request merged**
