### PR TITLE
pass_session_token_in_aws_creds

### PR DESCRIPTION
**Pull request by dhanya1**
## Checklist
Fixing the issue https://github.com/datahub-project/datahub/issues/7486, simple PR fixing role-based authentication for delta-lake ingestion.

### CODE REVIEW

**Review by treff7es — APPROVED** [review]
lgtm, thanks for the fix

**Review by treff7es — CHANGES_REQUESTED** [review]
It seems tests are failing

**Comment by jjoyce0510** [comment]
Merged as part of this PR! https://github.com/datahub-project/datahub/pull/7524#pullrequestreview-1334150871

**Comment by jjoyce0510** [comment]
Closing this PR accordingly. Thanks for the contrib!

**Pull request closed without merging**
