### PR TITLE
feat(ingestion/superset): add display_uri to config

### PR DESCRIPTION
**Pull request by milimetric**
Motivation: Superset can have complicated auth layers preventing direct
access through the main URI.  One way around this is to run a simpler,
private instance and use that for ingestion.  The problem is then that
the URIs in the links are pointing to the private instance.

Change: This change adds a base_uri parameter to the SupersetConfig
source configuration so that connect_uri can be where we ingest from and
base_uri can be used in links for dashboards, graphs, etc.  When absent,
this parameter defaults to connect_uri.

### CODE REVIEW

**Comment by milimetric** [comment]
Oops, looks like some linting problem, I'll update in a bit

**Comment by MugdhaHardikar-GSLab** [comment]
Changing parameter name to path_spec will make this change in sync with other sources like datalake, where base_path is skipped and path_spec is used for urn creation.

**Comment by milimetric** [comment]
@MugdhaHardikar-GSLab I see the [path_spec](https://github.com/datahub-project/datahub/blob/master/metadata-ingestion/src/datahub/ingestion/source/data_lake/config.py#L46) definition you're referencing but it seems a little different from this case.  In this case it's an alternative URI and not a path template.  I'm happy to change `base_uri` to something else, it's not a very good name either.  But `path_spec` felt like a different idea.

Also, from the testing results above, I see this failure but it doesn't seem to be related to this change, right?

```
datahub.spark.TestSparkJobsLineage > test4HiveInHiveOut FAILED
    java.lang.IndexOutOfBoundsException at TestSparkJobsLineage.java:363
    java.lang.AssertionError at TestSparkJobsLineage.java:133

datahub.spark.TestSparkJobsLineage > test5HdfsInJdbcOut FAILED
    java.lang.AssertionError at TestSparkJobsLineage.java:146
    java.lang.AssertionError at TestSparkJobsLineage.java:133

datahub.spark.TestSparkJobsLineage > test6HdfsJdbcInJdbcOutTwoLevel FAILED
    java.lang.AssertionError at TestSparkJobsLineage.java:146
    java.lang.AssertionError at TestSparkJobsLineage.java:133

datahub.spark.TestSparkJobsLineage > test7HdfsInPersistHdfsOut FAILED
    java.lang.AssertionError at TestSparkJobsLineage.java:146
    java.lang.AssertionError at TestSparkJobsLineage.java:133

datahub.spark.TestSparkJobsLineage > test8PersistHdfsJdbcInJdbcOut FAILED
    java.lang.AssertionError at TestSparkJobsLineage.java:146
    java.lang.AssertionError at TestSparkJobsLineage.java:133

datahub.spark.TestSparkJobsLineage > test9PersistJdbcInHdfsOut FAILED
    java.lang.AssertionError at TestSparkJobsLineage.java:146
    java.lang.AssertionError at TestSparkJobsLineage.java:133

10 tests completed, 6 failed
```

**Comment by MugdhaHardikar-GSLab** [comment]
Tests are irrevant to your change. Please ignore them. 
For field name, Can you consider 'display_uri' or similar? Or you can come up with something.

**Comment by milimetric** [comment]
> For field name, Can you consider 'display_uri' or similar? Or you can come up with something.

I like it!  Done.

**Review by MugdhaHardikar-GSLab — APPROVED** [review]
LGTM

**Review by treff7es — APPROVED** [review]
Lgtm

**Comment by milimetric** [comment]
@treff7es: sorry to bother, any idea on when this might make it to production?

**Pull request merged**
