### PR TITLE
refactor(ingest/openapi): add ability to parse defined schemas

### PR DESCRIPTION
**Pull request by alpolishchuk**
Add ability to parse schemas defined in specifications besides examples

- [x] The PR conforms to DataHub's [Contributing Guideline](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [x] Tests for the changes have been added/updated (if applicable)
- [x] Docs related to the changes have been added/updated (if applicable). If a new feature has been added a Usage Guide has been added for the same.
- [ ] For any breaking change/potential downtime/deprecation/big changes an entry has been made in [Updating DataHub](https://github.com/datahub-project/datahub/blob/master/docs/how/updating-datahub.md)

### CODE REVIEW

**Comment by hsheth2** [comment]
@alpolishchuk I haven't gotten a change to give this an in-depth review yet.

Two initial thoughts
- Our jsonschema parser has a bunch of support for resolving refs dynamically: https://github.com/datahub-project/datahub/blob/fdbc4de695c81be4aaf1d88d590cf5a60c5db722/metadata-ingestion/src/datahub/ingestion/source/schema/json_schema.py#L331 - is this reusing that logic, or reimplementing it because of some subtle differences
- More of an fyi - I'm planning on merging https://github.com/datahub-project/datahub/pull/8303 soon. I don't think those conflict in any way, but just want to double-check

**Comment by alpolishchuk** [comment]
@hsheth2 thank you for your reply!
1. I'll take a look on this parser and if it's applicable - will make changes
2. There shouldn't be any conflicts in logic, because my PR is about parsing schemas, and this PR is about parsing additional HTTP methods (but there will be merge conflicts for sure haha), so there wouldn't be any problems i guess

**Comment by shirshanka** [comment]
@coderabbitai full review

**Comment by hsheth2** [comment]
@alpolishchuk going to close this out for inactivity for now. If you get a chance to revisit this, we'll be happy to reopen the PR

**Pull request closed without merging**
