### PR TITLE
Fix: bug fix for empty key values pair in elastic search mapping

### PR DESCRIPTION
**Pull request by milindgupta9**
## Checklist

- [x] The PR conforms to DataHub's [Contributing Guideline](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md) (particularly [Commit Message Format](https://github.com/datahub-project/datahub/blob/master/docs/CONTRIBUTING.md#commit-message-format))
- [ ] Links to related issues (if applicable)
- [x] Tests for the changes have been added/updated (if applicable)
- [ ] Docs related to the changes have been added/updated (if applicable). If a new feature has been added a Usage Guide has been added for the same.
- [ ] For any breaking change/potential downtime/deprecation/big changes an entry has been made in [Updating DataHub](https://github.com/datahub-project/datahub/blob/master/docs/how/updating-datahub.md)

## Summary by CodeRabbit

- **New Features**
	- Enhanced handling of input format in search document processing to improve robustness.
	- Expanded capabilities of test entity information retrieval for more dynamic input.
  
- **Bug Fixes**
	- Improved prevention of runtime exceptions related to input string formats.

- **Tests**
	- Added new assertions in the test suite to validate the transformation logic, ensuring expected JSON structure.

### CODE REVIEW

**Review by david-leifker — APPROVED** [review]
Thanks!

**Comment by david-leifker** [comment]
@milindgupta9 - Please take a look at the test failures in the following module.
```
> Task :metadata-io:test FAILED
```

**Comment by milindgupta9** [comment]
@david-leifker your approval is required. Can you approve it?

**Comment by david-leifker** [comment]
@milindgupta9 - Please take a look at the failing `metadata-io:test`, from the log [here](https://github.com/datahub-project/datahub/actions/runs/10807962347/job/29996546405?pr=11004#step:7:1460).
```
879 tests completed, 3 failed, 71 skipped

> Task :metadata-io:test FAILED
```

**Comment by milindgupta9** [comment]
@david-leifker  I have fixed unit tests, can you take a pass now.

**Comment by milindgupta9** [comment]
Thanks @david-leifker for merging the PR

**Pull request merged**
